### PR TITLE
Update components.yaml

### PR DESCRIPTION
**Pull request by WilliamBZA**
Connects to https://github.com/Particular/docs.particular.net/issues/3596

### CODE REVIEW

**Comment by timbussmann** [comment]
LGTM. But is there any reason we're not linking to the specific repo now that those are unified (e.g. https://github.com/Particular/NServiceBus.Heartbeat)?

**Comment by WilliamBZA** [comment]
I would guess there might be people using the older packages? Similar to [this](https://github.com/Particular/PlatformDevelopment/issues/1334) discussion

**Comment by timbussmann** [comment]
@WilliamBZA according to this issue, the old repos are going to be deleted as the new ones contain tags for the old versions? Even more a reason to not link to a query I'd say?

**Comment by WilliamBZA** [comment]
@timbussmann Only V3 and V4 are being killed off. We still have V5 and V6 plugins.

**Pull request merged**
