### PR TITLE
WIP: License info log file

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by ramonsmits** [comment]
@Particular/docs-maintainers I created this based on log events I ran for a customer. Not sure if I should proceed and if it even is useful to have as documentation. There can be all kinds of license states that probably have different log output per major core version. ANy thoughts?

**Comment by DavidBoike** [comment]
I don't like having dates in there, you could probably start each message at the WARN/INFO or whatever.

This page is already versioned, should use partials not headings.

**Comment by HEskandari** [comment]
Also, need this for v6 and v7. The partials targetting those versions (in case there have been no changes) would solve that. Also, +1 on removing unimportant bits from the log. To me, the important parts are the log level and the message.

**Comment by ramonsmits** [comment]
@DavidBoike @HEskandari So you do think it has value? Then I will slowly finish this.

**Comment by HEskandari** [comment]
@ramonsmits I do believe it has value. I do get occasional questions about this. Haven't seen the related partials but consider adding few more details like maybe:

- When the performance is or is not degraded when the license is expired.
- Documenting the debugging mode experience (where a Window is shown)

**Comment by ramonsmits** [comment]
@HEskandari really good additions, I had the exact same questions Today about an expired license.

**Comment by SzymonPobiega** [comment]
Still WIP?

**Comment by SzymonPobiega** [comment]
Ping

**Pull request closed without merging**
