### PR TITLE
NServiceBus.Metrics references set to concrete alpha

### PR DESCRIPTION
**Pull request by tmasternak**
This PR is one of the steps in releasing `NServiceBus.Metrics` version 2.0 targeting `NServiceBus` 6.2+. This is needed as:
  * there is already `2.0.0-alpha0027` published to myget targeting 7.0 of core
  * we want to be able to publish `2.0.0-beta` targeting 6.2+ of core

In next steps we will to update this doco to version `2.0` and when version `3.0` is out we will reintroduce .NetCore sample.

### CODE REVIEW

**Comment by SimonCropp** [comment]
so metrics v3 will now target nsb v7?

**Comment by SimonCropp** [comment]
what breaking changes are coming in v2?

**Comment by tmasternak** [comment]
In v2 are obsoletes parts of public Api.

**Comment by Scooletz** [comment]
@SimonCropp `so metrics v3 will now target nsb v7?` - yes

**Comment by SimonCropp** [comment]
in that case this PR should also add v3 snippets and samples for metrics

**Comment by Scooletz** [comment]
@SimonCropp This PR aims at locking the version of Metrics for now to enable us to move forward with changes and stop autobump for now. Once we've got 2.0 and 3.0 ready (this includes `NSB.Metrics`, `NSB.Metrics.PerformanceCounters`, `NSB.Metrics.ServiceControl`) we'll issue a separate PR addressing 2.0 and 3.0

**Comment by SimonCropp** [comment]
is there some complexity with releasing a v3 NSB.Metrics?

also given NSB.Metrics is not on nuget u can delete the packages from myget and keep the wildcard

**Comment by Scooletz** [comment]
We can but we don't want to break the build. Freezing it to the current one, will give us time to publish next, without breaking build, and send a follow up PR moving doco to the new version.

**Pull request merged**
