### PR TITLE
[WIP] routing pubsub refactoring

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Updates the routing doco for https://github.com/Particular/NServiceBus/pull/3816

### CODE REVIEW

**Comment by johnsimons** [comment]
Some inconsistencies in the API:
```C#
var routing = endpointConfiguration.Routing();
routing.RouteToEndpoint(typeof(MyMessage), "MyEndpoint");
```
```c#
var transport = endpointConfiguration.UseTransport<UnicastTransport>();           
transport.RegisterPublisherForType("Sales", typeof(MyEvent));           
transport.RegisterPublisherForAssembly("Sales", typeof(OtherEvent).Assembly);
```
So in the first code block we have `routing.RouteToEndpoint(typeof(MyMessage), "MyEndpoint");` and in the second the parameter order is inverse `transport.RegisterPublisherForType("Sales", typeof(MyEvent));`

I think it would make sense to make them the same order, thoughts ?

**Comment by johnsimons** [comment]
Also I wonder if we could have a simpler syntax like:
```
routing.RouteToEndpoint<MyMessage>("MyEndpoint");
```

**Comment by johnsimons** [comment]
This is confusing, and the doco api does not help (it is the same for both):
image
and
image

**Comment by johnsimons** [comment]
image

These seem to be "advanced apis" do we really need to expose them at the root level ?

**Comment by SimonCropp** [comment]
@johnsimons your feedback should be targeted at the NSB repo not the doco repo

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Particular/docs.particular.net/commit/a4c4507417d7e48d530552f08ece7e16ae2f06f9

**Pull request closed without merging**
