### PR TITLE
[WIP] Low-friction migration from V5 sample

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by weralabaj** [comment]
what's that related to?

**Comment by SzymonPobiega** [comment]
to a customer case -- upgrading from 4/5 to 6. This sample was meant to make it easier to upgrade. I'll continue working on it if it proves valuable to the customer.

**Comment by SimonCropp** [comment]
@SzymonPobiega did it prove valuable?

**Comment by SzymonPobiega** [comment]
I got no feedback from them. Asked a couple of times :-(

**Comment by SimonCropp** [comment]
so close this one?

**Comment by SzymonPobiega** [comment]
😢

**Comment by SzymonPobiega** [comment]
I got a positive feedback from the user. I think it gives me enough motivation to clean up and finish this one.

**Comment by SimonCropp** [comment]
@SzymonPobiega should this branch be deleted?

**Pull request closed without merging**
