### PR TITLE
Tweaks in aws-lambda-simple-queue-service.md

### PR DESCRIPTION
**Pull request by tmasternak**

### CODE REVIEW

**Review by SzymonPobiega — APPROVED** [review]

**Review by WilliamBZA — APPROVED** [review]

**Comment by udidahan** [comment]
You also have this in the Delayed Retries section.

**Comment by udidahan** [comment]
Is it reasonable to assume that this was copy-pasted from the Azure functions content?
If so, can you also open a PR to fix it there?
Thanks.

**Comment by WilliamBZA** [comment]
These sections weren't copied over.

Azure has a [dedicated provisioning section](https://docs.particular.net/previews/azure-functions-service-bus#preparing-the-azure-service-bus-namespace):

> Function endpoints cannot create their own queues or other infrastructure in the Azure Service Bus namespace.
> 
> Use the asb-transport command line (CLI) tool to provision the entities in the namespace for the Function endpoint.

**Comment by WilliamBZA** [comment]
Copied over to #4994

**Comment by udidahan** [comment]
👍

**Pull request merged**
