### PR TITLE
update metrics

### PR DESCRIPTION
**Pull request by SimonCropp**
@Particular/metrics-maintainers cant work out what the fix is for this. is there an upgrade guide?

### CODE REVIEW

**Comment by SimonCropp** [comment]
ignore the rabbit error. that is fixed on master

**Comment by SimonCropp** [comment]
given this could effect users, is there an upgrade guide?

**Comment by dvdstelt** [comment]
@SimonCropp I don't see any upgrade guide for any minor version? And the tooltip provides all the information needed, as far as I'm concerned? It's just that doco wasn't properly updated. I'm also not too sure about the warning, but at least now the build (should) work.

**Comment by dvdstelt** [comment]
Yes, build just succeeded, only error left is Rabbit error.

**Comment by SimonCropp** [comment]
@dvdstelt thanks

**Pull request merged**
