### PR TITLE
Added woff2 config instructions

### PR DESCRIPTION
**Pull request by petersgiles**
fixes: https://github.com/Particular/ServicePulse/issues/230

### CODE REVIEW

**Comment by petersgiles** [comment]
Waiting on installation of SSL cert for particular.net

**Comment by petersgiles** [comment]
@SimonCropp have withdrawn the version text SSL instructions and focused in on what is necessary within the context of the rest of the info on the page including advanced configuration. @gbiellem and I have verified that the adding the mimetypes works

**Comment by gbiellem** [comment]
@petersgiles @SimonCropp   I thought we were going to improve this further before merging. It's still not very good

**Comment by SimonCropp** [comment]
@gbiellem sorry i took @petersgiles comment to mean it was done

**Comment by petersgiles** [comment]
The whole document needs a rewrite. The story it tells is a bit fractured. I was going to close this off and then start a new edit focused on making the whole thing better

**Pull request merged**
