### PR TITLE
Added missing snippet and clarified that MEM is still supported in V6.

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@SzymonPobiega this is the first i have hear that MessageEndpointMappings is considered legacy as of v6. can u point me to where the discussion/decision happened regarding this

**Comment by johnsimons** [comment]
@SimonCropp this is all about the new routing code only api.
It is referred to in first paragraph of http://docs.particular.net/nservicebus/messaging/message-owner

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah, legacy might be a bit of a strong word. I wanted to encourage people to use code-first type-to-endpoint mappings.

**Comment by SimonCropp** [comment]
@SzymonPobiega so just make the new API easier to use. 

but can u remove the comments about legacy from this

**Pull request merged**
