### PR TITLE
Updating nhibernate samples and snippets

### PR DESCRIPTION
**Pull request by WojcikMike**
To use the latest Beta

### CODE REVIEW

**Comment by weralabaj** [comment]
> <HintPath>..\..\..\packages\NServiceBus.6.0.0-beta0007\lib\net452\NServiceBus.Core.dll</HintPath>

Is that right? Should Core be beta0007?

**Comment by WojcikMike** [comment]
Yep, Beta0007 hot from the press

**Comment by WojcikMike** [comment]
@Particular/docs-maintainers please merge

**Comment by weralabaj** [comment]
Does that mean that all the downstreams also should be 0007? That's besides the subject of this PR, but that's confusing.

**Pull request merged**
