### PR TITLE
[wip] NServiceBus.AmazonSQS transport

### PR DESCRIPTION
**Pull request by ahofman**
First pass documentation for the NServiceBus.AmazonSQS transport.

For the most part this is a lift-and-shift of some of the documentation in the old [project wiki](https://github.com/ahofman/NServiceBus.AmazonSQS/wiki), with some small updates.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Will get to this to tomorrow

**Comment by SimonCropp** [comment]
First thing. For these type of pages there is no personal voice https://github.com/Particular/docs.particular.net#language-preferences
Let me know if u need help coaching over

**Comment by SimonCropp** [comment]
@ahofman i had to do this https://github.com/Particular/docs.particular.net/pull/2836/commits/196cfe4b50d04ab22ff82a435a4ed2adcbe0c285  to work around this https://github.com/ahofman/NServiceBus.AmazonSQS/pull/75/files

**Comment by ahofman** [comment]
Thanks @SimonCropp, I'll fix tomorrow.

**Comment by SimonCropp** [comment]
i fixed the build error with the components. i will give the content a full review tomorrow

**Comment by SimonCropp** [comment]
@ahofman i am happy with the current state. happy for me to merge?

**Comment by ahofman** [comment]
I'm happy for you to merge, thanks for your help on this @SimonCropp :)

**Comment by SimonCropp** [comment]
https://docs.particular.net/nservicebus/sqs/  :)

**Pull request merged**
