### PR TITLE
Review host logging page

### LINKED ISSUE #2079: The page 'Logging' requires review
The page [Logging](https://docs.particular.net/nservicebus/hosting/nservicebus-host/logging) has never been reviewed.
- [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
- [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/nservicebus/hosting/nservicebus-host/logging.md)

### PR DESCRIPTION
**Pull request by bording**
Closes #2079

### CODE REVIEW

**Comment by SimonCropp** [comment]
U don't thnk version switching on that page would be useful?

**Comment by bording** [comment]
I suppose it would be useful, but it didn't occur to me to try and change it. What all is involved in making that conversion?

**Comment by SimonCropp** [comment]
https://github.com/Particular/docs.particular.net#markdown-partials

**Comment by SimonCropp** [comment]
@bording do u want me to add a commit to this PR that moves it to version switching to illustrate?

**Comment by bording** [comment]
I know how to add the partials, so I can do that. Is there something that has to be added to the main page to opt it in to the versioning/partials mode?

**Comment by bording** [comment]
@SimonCropp I pushed up a change that adds partials, and looking at other pages, I added the component header to the main page.

How does that look?

**Comment by SimonCropp** [comment]
Lgtm

**Pull request merged**
