### PR TITLE
Improving MessagingBestPractices/Validations exception messages

### PR DESCRIPTION
**Pull request by WojcikMike**
Adding information about exceptions being thrown while violating the best practices

Relates to https://github.com/Particular/NServiceBus/issues/3267

### CODE REVIEW

**Comment by SimonCropp** [comment]
is the exception message consistent for all current majors of NSB?

**Comment by WojcikMike** [comment]
The above description match NSB v6.

For NSB v5 the messages are the same however the exception is of type `InvalidOperationException`

NSB v4 and v3 - as for NSB v5 the exception is `InvalidOperationException` and the following message:
"Reply is neither supported for Commands nor Events. Commands should be sent to their logical owner using bus.Send and bus. Events should be Published with bus.Publish."
Depends on the method used you either get the same message or 2 separate ones:
"Reply is not supported for Commands. Commands should be sent to their logical owner using bus.Send and bus."
and
"Reply is not supported for Events. Events should be Published with bus.Publish."

@SimonCropp should we extract the section with exceptions and do it in a way that match versions?

**Comment by WojcikMike** [comment]
Hey @andreasohlund , can you chime in?

**Comment by SimonCropp** [comment]
@WojcikMike i dont care about the exception type. people should never be catching it so it is irrelevant.   i would like to have the exact text for each major version captured in the doco

**Comment by andreasohlund** [comment]
> i dont care about the exception type. people should never be catching it so it is irrelevant. i would like to have the exact text for each major version captured in the doco

:+1:

**Comment by WojcikMike** [comment]
Ok, in that case this is the direction that I will taken. Will include exact exception messages without mentioning exception types.

**Pull request merged**
