### PR TITLE
Note on reverting SC hostname to localhost

### PR DESCRIPTION
**Pull request by ramonsmits**
Based on support call.

### CODE REVIEW

**Comment by WilliamBZA** [comment]
Tweaked some of the grammar, but what is the context here?

**Comment by ramonsmits** [comment]
@WilliamBZA Customer had configure a remote host, found out that it wasn't secure even though it uses IIS with ARR. Requested support, and I saw that it was not using localhost. Ran SCMU, set it to localhost so that the SC was not remotely accessible anymore.

**Comment by ramonsmits** [comment]
Rebased to trigger new build

**Comment by ramonsmits** [comment]
@WilliamBZA Can this be merged?

**Pull request merged**
