### PR TITLE
Be explicit about netcore license locations

### PR DESCRIPTION
**Pull request by DavidBoike**
References:

### Windows

Well, mostly LinqPad, but [this is source for both](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Win32.cs#L65-L70).

### Linux/macOS
* [LocalApplicationData](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L139-L147)
* [CommonApplicationData](https://github.com/dotnet/corefx/blob/v2.0.6/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L101)

### CODE REVIEW

**Comment by timbussmann** [comment]
I think this definitely needs a "by default [...]" when mentioning the specific locations. Maybe even a note or statement that these values might differ depending on the OS configuration.

**Comment by DavidBoike** [comment]
@timbussmann Do you think that .NET Core code will change?

**Comment by DavidBoike** [comment]
I do think we might need a statement about expanding the environment variables, or that the variables for Linux/macOS are presented in bash syntax, but I'm not sure how to word that. I'm not actually that good at bash, I'm leaning on what @bording came up with for our trial extension email that uses the same paths to tell you how to install your license.

**Comment by bording** [comment]
I think we need the wording here to indicate that we're using `SpecialFolder.LocalApplicationData` and `SpecialFolder.CommonApplicationData` in our code, and that those map to the indicated locations based on the OS.

I'm also wondering if we should split the "machine-wide" locations out into a "per-user" section and the actual "machine-global" location.

**Comment by DavidBoike** [comment]
What do you think now @bording?

**Pull request merged**
