### PR TITLE
Add info for message type fallback

### PR DESCRIPTION
**Pull request by dvdstelt**
I added a single paragraph. But although it might be clear or correct what it states (I have you to verify that ;-) ) I'm not sure of readers of the document will understand.

I've thought about a code snippet of a single line, which seems ridiculous. Also because it's not NSB version related, it's .NET related.
I've also thought about putting a triple ` addition, like in the step-by-step page (http://docs.particular.net/samples/step-by-step/)
But I'm not sure if I'm allowed to use that.

So I'd like some feedback

### CODE REVIEW

**Comment by dvdstelt** [comment]
This is the line I might add, to show how to obtain the FQN

```
MyCustomMessage message = new MyCustomMessage();
string fqn = message.GetType().AssemblyQualifiedName;
```

**Comment by SimonCropp** [comment]
@dvdstelt perhaps `typeof(MyCustomMessage).AssemblyQualifiedName` etc?

**Comment by SimonCropp** [comment]
@andreasohlund can u please review this

**Comment by dvdstelt** [comment]
@SimonCropp I thought that with the message coming into a handler, the `message.GetType()` would be clearer to the readers. To make it more clear, I added the `MyCustomMessage message = new MyCustomMessage();` so they'll know it's the message coming into a handler.

Might also change it to the following. But thought that was overkill, as you also need to add a async NSB6 version for people to understand it in the near future.

```
public class MyHandler : IHandleMessages<MyMessage>
{
    public void Handle(MyMessage message)
    {
        string fqn = message.GetType().AssemblyQualifiedName;
        string fallback = message.GetType().FullName;
    }
}
```

**Comment by SimonCropp** [comment]
@dvdstelt there is actually a way to document that kind of stuff in a cross version way https://github.com/Particular/docs.particular.net#defining-snippets

**Comment by dvdstelt** [comment]
I know. And with the last snippet it might make sense, because the IHandleMessages<T> code is in there. But initially it was just C# code which doesn't change over NServiceBus versions (yet) and I thought the snippets were a bit overkill.

Normally I write much sentences to explain something. But as NServiceBus docos normally don't use a lot of words/sentences, I thought I'd comply (?) to this as well and made up just this paragraph.

But that's also why I asked to have a look at what I wrote. Should I add the code? Should I use more words to explain? I know to me personally, the paragraph would probably not make a lot of sense and I'd need to study it. Especially without a code example.

**Comment by SimonCropp** [comment]
wouldnt this be better documented here http://docs.particular.net/nservicebus/messaging/headers#serialization-headers

**Comment by dvdstelt** [comment]
It's not where I would look for information on how messages are mapped to handlers. It could be a reference from the handlers doc to the headers doc, where it's explained further. But I've looked at the headers document as a reference for information, not where something is explained about how a mapping occurs.

**Pull request merged**
