### PR TITLE
WCF to messaging menu

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by indualagarsamy** [comment]
@danielmarbach - I think under Endpoints in Hosting will be a better location for this. 
https://docs.particular.net/nservicebus/endpoints/

Thoughts?

**Comment by danielmarbach** [comment]
I thought about that too but actually it is no longer hosting related. You
could argue the feature hosts WCF services but actually it is about sending
messages from WCF to the bus isn't it?

**Comment by indualagarsamy** [comment]
@danielmarbach - true. However the title of the doco is `Exposing Endpoints via WCF`.

**Comment by danielmarbach** [comment]
Nothing we can't change ;)

**Pull request merged**
