### PR TITLE
Adjust saga concurrency doco to better explain different concurrency resolution strategies

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
@danielmarbach @timbussmann fyi

**Comment by andreasohlund** [comment]
@Particular/sqlpersistence-maintainers @Particular/nhibernate-persistence-maintainers @Particular/ravendb-persistence-maintainers can you help me review the new docs for you specific persister and see if I missed anything? (or if I duplicated info by misstake)

@timbussmann @danielmarbach  can you review as well based on our recent discussion around sagas

@Particular/docs-maintainers please review

**Comment by SimonCropp** [comment]
should be in menu?

**Comment by SimonCropp** [comment]
do the raven and sql pages need to be new pages?

**Comment by andreasohlund** [comment]
>do the raven and sql pages need to be new pages?

Just copy pasted the NH one, thinking that we will be adding plenty  of info here? (eg when the SqlPersister gets it "pessimistic" locking mode etc.)

**Comment by andreasohlund** [comment]
>should be in menu?
Yea, will add

**Pull request merged**
