### PR TITLE
Custom routing refresh exception handling

### PR DESCRIPTION
**Pull request by ramonsmits**
Current implementation crashed when there is a temporary error on the database. Also have execution overlap protection added in case the refresh operation duration is larger then the timer interval period.

### CODE REVIEW

**Comment by ramonsmits** [comment]
@Particular/nservicebus-maintainers At runtime the startup tasks fail to initialize. I can't seem to be able to do `builder.Build<RoutingInfoCommunicator>(),`.

Any idea why?

**Comment by danielmarbach** [comment]
@ramonsmits yes that is not possible. RegisterStartupTask doesn't register anything on the container. The previous code did it right, it declared the communicator as a local and then added the local to the startup task list and passed the local to the other instances that needed it. 

As I see the problem is here that you need to get access to CriticalError and as of now CriticalError is only exposed on the container but not on the settings. This forces you to use the builder. I'll send it a PR with a suggestion

**Comment by danielmarbach** [comment]
Please see https://github.com/Particular/docs.particular.net/pull/2502

**Comment by ramonsmits** [comment]
@Particular/docs-maintainers This is ready for merging. Based on a customer that had stability issues after adopting the sample in their code base.

**Pull request merged**
