### PR TITLE
SC TransportAdapter for ASB and Core v7

### PR DESCRIPTION
**Pull request by SeanFeldman**
Sample for SC ASB transport adapter with NServiceBus v7

**Blocked** until ASB PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/696 is merged

### CODE REVIEW

**Comment by SeanFeldman** [comment]
Closing in favour of #3557

**Comment by SeanFeldman** [comment]
Blocked until ASB PR Particular/NServiceBus.AzureServiceBus#696 is merged

**Comment by SeanFeldman** [comment]
@SzymonPobiega review and merge?

**Comment by SeanFeldman** [comment]
samples/snippets fail with unrelated error (RavenDB)

**Comment by SzymonPobiega** [comment]
I rebased it. Hopefully it builds this time.

**Comment by SeanFeldman** [comment]
It's green, merging. Thanks @SzymonPobiega

**Pull request merged**
