### PR TITLE
when using serilog should use ILogger for logging

### PR DESCRIPTION
**Pull request by SimonCropp**
related to https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/18

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@SimonCropp if the user code is not using NSB logging abstraction but the Serilog directly, do you think there is still purpose for keeping this sample? It seems a bit redundant to me -- it's like documenting Serilog's APIs.

**Comment by SimonCropp** [comment]
@SzymonPobiega it is not "documenting how to log in serilog". it is illustrating how to use NSB.Serilog with NSB. that includes the config code. it also gives people a significant leg up if someone wants to spike the use of Serilog with NSB, since they can download a runnable sample

**Comment by SzymonPobiega** [comment]
The build failures are not relevant to this change so merging.

**Comment by SimonCropp** [comment]
@SzymonPobiega u might want to review the other logging doco in the context of this 
https://github.com/NServiceBusExtensions/NServiceBus.Serilog/issues/18#issuecomment-412000989

**Pull request merged**
