### PR TITLE
Update NHibernate concurrency information

### PR DESCRIPTION
**Pull request by DavidBoike**
Ping @Particular/nhibernate-persistence-maintainers:

I tried to explain the concurrency model in NHibernate sagas better, see if you agree with me. I also thought it was weird that we were linking to a post in Ayende's blog (click on something for NHibernate and go to the Raven guy's blog?) especially when we cover the [RowVersion] attribute in our own docs. I also objected to the phrase "so that NHibernate can work its magic" which doesn't sound like it belongs in docs.

### CODE REVIEW

**Comment by indualagarsamy** [comment]
@DavidBoike - can you fix the build error regarding the link:

```
  ----> System.Exception : Failed to render article. PackageId:NServiceBus. Version:[6.0.0, ).
  ----> ErrorsException : Error:'Path does not exist'. Url:'/nservicebus/nhibernate/saga-concurrency#explicit-version'.
```

**Comment by DavidBoike** [comment]
Can't link to hashes I take it?

**Comment by SimonCropp** [comment]
U r missing the .md extension

**Comment by MarcinHoppe** [comment]
I like the new description.

**Pull request merged**
