### PR TITLE
adding details about v6

### PR DESCRIPTION
**Pull request by mauroservienti**
@Particular/ravendb-persistence-maintainers please review

### CODE REVIEW

**Comment by DavidBoike** [comment]
This is merged and that's fine, but should we consider changing the "Supported NServiceBus Versions" heading into a table that shows the targeted NSB and Raven versions?

Like this:

| NServiceBus.RavenDB | NServiceBus Core | RavenDB.Client |
|:-------------------:|:----------------:|:--------------:|
|         4.x         |        6.x       |      3.0.x     |
|         3.x         |        5.x       |      3.0.x     |
|         2.x         |        5.x       |      2.5.x     |
|         1.x         |     4.1 - 4.x    |      2.5.x     |

**Comment by SimonCropp** [comment]
@DavidBoike i would prefer to see that generated from info in nuget

**Comment by DavidBoike** [comment]
@SimonCropp: And for **every** component, correct?

**Comment by SimonCropp** [comment]
yes that would be a side effect.

**Pull request merged**
