### PR TITLE
[WIP] Documenting support for TLS in Rabbit v3.2

### PR DESCRIPTION
**Pull request by johnsimons**
This links to https://github.com/Particular/NServiceBus.RabbitMQ/pull/147

### CODE REVIEW

**Comment by johnsimons** [comment]
@Particular/rabbitmq-transport-maintainers please review

**Comment by SimonCropp** [comment]
looks good. merge when u release

**Comment by johnsimons** [comment]
thanks @SimonCropp

**Comment by SimonCropp** [comment]
@johnsimons if ok with u, i will bump the nugets when i get the email notification for the nuget being deployed ??

**Pull request merged**
