### PR TITLE
RavenDB Persistence:  note reminding to do dispose the user created document store

### LINKED ISSUE #3035: Feedback: 'RavenDB Persistence'
Feedback for 'RavenDB Persistence' https://docs.particular.net/persistence/ravendb/ and https://docs.particular.net/samples/ravendb/simple/

ping @Particular/ravendb-persistence-maintainers

should we be disposing of `DocumentStore` on endpoint shutdown? or add a note reminding people to do so?

### PR DESCRIPTION
**Pull request by mauroservienti**
Connects to #3035 
Fix #3035

### CODE REVIEW

**Comment by DavidBoike** [comment]
Looks good, although it could be an include. Should it be referenced from the [Custom Saga Finder sample](https://docs.particular.net/samples/saga/ravendb-custom-sagafinder/) sample too?

@SimonCropp wondering what your motivation in #3035 was though. Doesn't this fall into the bucket of reminding developers to dispose things that are disposable? Should we really be taking responsibility for that?

**Comment by SimonCropp** [comment]
> Doesn't this fall into the bucket of reminding developers to dispose things that are disposable

yeah i dont really like that either. but AFAIK everywhere else we have disposable stuff we put it in a using or clean it up. in the raven sample we should definitely clean it up. i think it is fine not to explain the obvious that is outside the scope of the NSB domain, but this is a grey area. eg here https://docs.particular.net/persistence/ravendb/#shared-session can i scope the store in a using?  that would seem to be the correct assumption to make. when in reality they need to clean it up on endpoint shutdown

**Comment by mauroservienti** [comment]
Can an include be referenced by a document not in the same folder? The sample.md is in a different folder and needs the same include

**Comment by SimonCropp** [comment]
includes are global and can be located anywhere and included in any file

**Comment by SimonCropp** [comment]
and u can ignore the build error. it is fixed on master

**Comment by SimonCropp** [comment]
and yes i think it should be an include. but i think the samples should correctly dispose of the document store

**Comment by DavidBoike** [comment]
I think we should dispose the DocStore too. Just toss it in a using after Initialize that ends after the endpoint is stopped on the relevant Program.cs files.

**Comment by DavidBoike** [comment]
In fact, if we do dispose the DocStore, I'm not even sure we really need to have the info boxes to tell developers to dispose disposable things. Putting it in a using would get the message across effectively enough.

**Comment by SimonCropp** [comment]
@DavidBoike i think for the samples that makes sense. but, for example, i could not work out how to have a using that conveys the same thing here https://docs.particular.net/persistence/ravendb/connection#external-store-at-initialization-for-a-specific-persister

**Comment by DavidBoike** [comment]
Hmmm, yeah that's a problem. Guess a NOTE is better than the gymnastics to include all the disposes in that snippet.

**Comment by SimonCropp** [comment]
but either way i think the snippet here https://docs.particular.net/persistence/ravendb/connection#external-store-at-initialization-for-a-specific-persister needs tweeking. since from the usage i see there i would assume that the underlying persister will handle the dispose for me. at least that is what having the construction of the store scoped inside the delegate implies

**Pull request merged**
