### PR TITLE
Add websocket gateway sample for gateway 3 and core 7

### PR DESCRIPTION
**Pull request by mauroservienti**
At the moment `WebSocketSharp` [does not support .NET Core, yet](https://github.com/sta/websocket-sharp/issues/412). Adding full framework sample only.

### CODE REVIEW

**Comment by mauroservienti** [comment]
I'm referencing packages using an explicit version, since if I use a wildcard reference I get the following nuget error when restoring packages:

> NU1102
> Unable to find package NServiceBus with version (>= 7.0.0)
>   - Found 665 version(s) in nuget.org [ Nearest version: 7.0.0-beta0012 ]
>   - Found 126 version(s) in particular myget.org [ Nearest version: 7.0.0-beta0013 ]
>   - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Comment by mauroservienti** [comment]
I reviewed the solution, the sample works just fine. As far as I can tell this is marked as WIP simply because we're waiting for `WebSocketSharp` to support .NET Core. As soon as https://github.com/sta/websocket-sharp/issues/412 is done, we can go ahead.

Otherwise we can merge this as is. I'm subscribed to https://github.com/sta/websocket-sharp/issues/412 and I'll raise a PR to add multi-targeting support as it is fixed.

@weralabaj @SzymonPobiega thoughts?

**Comment by weralabaj** [comment]
Let's merge as is and set reminders to check the status of the websocket in 2/4 weeks, ok?

**Comment by mauroservienti** [comment]
Wip removed, @weralabaj @SzymonPobiega care to do a quick review and merge if you’re happy?

**Comment by weralabaj** [comment]
I'm getting warnings so I think we should go for code config to get rid of warnings and update the text as needed:

capture

**Comment by mauroservienti** [comment]
@weralabaj please take a look, configuration moved from config file to code.

**Pull request merged**
