### PR TITLE
[WIP] V6 store and forward

### PR DESCRIPTION
**Pull request by johnsimons**
This deals with #1168 

Stuck on how to access the send options in v6, have no idea how to do it

### CODE REVIEW

**Comment by SimonCropp** [comment]
@timbussmann can u comment on this

**Comment by timbussmann** [comment]
`SendOptions` are not available in the pipeline. All settings configured on the `SendOptions` are merged into the pipeline context (e.g. see here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs#L17).

**Comment by johnsimons** [comment]
@timbussmann I need access to the send type, so I can distinguish whether is a publish or a send ?
This is how we used to do it in v5:
```c#
SendOptions sendOptions = context.DeliveryOptions as SendOptions;
 +        if (sendOptions != null)
 +        {
 +            context.OutgoingLogicalMessage.Headers["$.store-and-forward.destination"] =
 +                sendOptions.Destination.ToString();
 +            sendOptions.Destination = configure.LocalAddress;
 +            //We could as well store other properties of the SendOptions to handle things like delayed delivery
 +        }
 +        else
 +        {
 +            PublishOptions publishOptions = context.DeliveryOptions as PublishOptions;
 +            if (publishOptions != null)
 +            {
 +                //Technically we don't need to store tha actual type, just a marker that this is a Publish operation
 +                context.OutgoingLogicalMessage.Headers["$.store-and-forward.eventtype"] =
 +                    publishOptions.EventType.AssemblyQualifiedName;
 +            }
 +            else
 +            {
 +                //We should never get here as is makes no sense to reply from outside of a handler
 +                throw new NotSupportedException("Not supported delivery option: " + context.DeliveryOptions.GetType().Name);
 +            }
 +        }
```

How can I achieve the same in v6 ?

**Comment by timbussmann** [comment]
can you use `IOutgoingLogicalMessageContext.Message.MessageType`?

**Comment by johnsimons** [comment]
@timbussmann 

> can you use IOutgoingLogicalMessageContext.Message.MessageType

Not sure, u tell me ?

**Comment by timbussmann** [comment]
@johnsimons it should work. Since it's your PR, you should be able to test it yourself?

**Comment by johnsimons** [comment]
@timbussmann I have tested it and still stuck

I assume this is what u mean:
```
if (conventions.IsEventType(context.Message.MessageType))
```
Is the `context.Message.MessageType` the eventtype or the proxy type ?

Also I need to get access to the destination, how do I get that ?

**Comment by johnsimons** [comment]
@timbussmann I really think u should take over this PR, it is not much left to do.

**Comment by timbussmann** [comment]
@johnsimons what about this comment in the linked issue here:

> correct we decided to drop multi-DB/outbox combo in v6 so the sample does not really make sense.

do we still need this sample at all then?

**Comment by johnsimons** [comment]
@timbussmann not my call, as I said in https://github.com/Particular/docs.particular.net/issues/1168#issuecomment-188621568

**Comment by timbussmann** [comment]
closing this as #1168 was closed to

**Pull request closed without merging**
