### PR TITLE
ASB-MSMQ Bridge sample Core v7 / ASB v8

### PR DESCRIPTION
**Pull request by SeanFeldman**
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/504
Continuation of #3358 

~~**BLOCKED** by changed required in NServiceBus.Bridge for Core v7~~

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Settings bug is fixed now. But there is another one. It seems like the barcher used in the sending is accessing the "SharedQueue" settting earlier than in V7. This requires a fix in NSB.Raw...

**Comment by SeanFeldman** [comment]
There's an outstanding issue for ASB (PR https://github.com/Particular/NServiceBus.AzureServiceBus/pull/657), though it's for readonly endpoints.

The Batcher in ASB will be using `settings.LocalAddress()`.

**Comment by SeanFeldman** [comment]
NSB.ASB beta4 is on MyGet. It includes serializer guard and LocalAddress fixes.

**Comment by SeanFeldman** [comment]
- Serializer issue, workaround is still needed as Bridge is creating endpoint on ASB transport and serializer is not set. (@SzymonPobiega could you confirm?)
- "The given key (NServiceBus.SharedQueue) was not present in the dictionary." is still thrown. ASB `Batcher` is using `Settings.LocalAddress()` for a normal (not send-only) endpoint.

Given that `Settings.LocalAddress()` should be used to retrieve an endpoint address, is this an issue with NSB.Raw @SzymonPobiega ?

**Comment by indualagarsamy** [comment]
@SeanFeldman - Can you add the markdown file that explains the sample?

**Comment by SeanFeldman** [comment]
It's already in place @indualagarsamy. Was a part of https://github.com/Particular/docs.particular.net/pull/3358

**Comment by SeanFeldman** [comment]
@Particular/docs-maintainers if no one opposes, this can be merged

**Pull request merged**
