### PR TITLE
[WIP] Upgrading RavenDB sample to NServiceBus v6

### PR DESCRIPTION
**Pull request by johnsimons**

### CODE REVIEW

**Comment by johnsimons** [comment]
Stuck on getting access to the async session (`IAsyncSessionProvider`).

Anyone knows how I get access to it ?

**Comment by mauroservienti** [comment]
on it

**Comment by johnsimons** [comment]
Have submitted a [PR to ravendb](https://github.com/Particular/NServiceBus.RavenDB/pull/153) to get unstck, waiting on it to be merged in

**Comment by SimonCropp** [comment]
@johnsimons i think we crossed the streams here. my fault so i will handle the merge of this tomorrow

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Particular/docs.particular.net/commit/99e5b12a18769b993e083f2fcb12e6dc9225fe85 and https://github.com/Particular/docs.particular.net/commit/e38156b0e66ff6261f026695886ed4d22011936b

**Pull request closed without merging**
