### PR TITLE
Updates to ServiceControl for v1.13.0

### PR DESCRIPTION
**Pull request by johnsimons**
Connects to https://github.com/Particular/PlatformDevelopment/issues/667.

This PR has the reuired updates to the ServiceControl doco as part of the changes in v1.13.0.

The changes are documented in:
- https://github.com/Particular/ServiceControl/pull/694

### CODE REVIEW

**Comment by johnsimons** [comment]
@gbiellem all yours from here :wink:

**Comment by gbiellem** [comment]
@johnsimons  renamed PR as discussed - Will do a seperate PR for the v1.12 changes.

**Comment by johnsimons** [comment]
@gbiellem @mikeminutillo I have just rebased this one and I think is ready for last review so it is ready to go once we release 1.13

**Comment by gbiellem** [comment]
@johnsimons I need to do one more pass on this to makes sure I have not missed anything

**Comment by indualagarsamy** [comment]
@gbiellem - is this PR ready to be merged when 1.13.0 has been released?

**Comment by gbiellem** [comment]
@indualagarsamy it needs a review.  I think @SimonCropp  wanted to chnage some stuff but was holding off my final changes which are now in

**Comment by SimonCropp** [comment]
this is good to merge when u release

**Comment by gbiellem** [comment]
Thanks @SimonCropp

**Pull request merged**
