### PR TITLE
Update to ServicePulse installation parameters & defaults

### PR DESCRIPTION
**Pull request by dvdstelt**
Related to https://github.com/Particular/ServicePulse/issues/443

### CODE REVIEW

**Comment by dvdstelt** [comment]
@Particular/servicepulse-maintainers Do we want to doco this and are these all the parameters?

**Comment by TraGicCode** [comment]
Anyone wanting to perform infrastructure as code with chef or puppet would really love to be able to utilize this flexibility and also understanding how/where to change these settings after initial install

**Comment by weralabaj** [comment]
I think it looks good, once we get this question answered "are these all the parameters?" I'll merge.

**Comment by WilliamBZA** [comment]
@weralabaj I'll confirm re the parameter list shortly.

**Comment by mikeminutillo** [comment]
Port and SC Uri are the only 2 configuration parameters that are specific to ServicePulse. I'm :+1: for this change.

**Pull request merged**
