### PR TITLE
Introduction section

### PR DESCRIPTION
**Pull request by ramonsmits**
@yvesgoeleven I think it needs an introduction.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Please fix the personal  voice

**Comment by ramonsmits** [comment]
@SimonCropp done that. As its a PR on  your doco PR @yvesgoeleven can you check if this is valuable to start the content with?

**Comment by yvesgoeleven** [comment]
@ramonsmits I incorporated it in the other PR, some parts kept as intro, but other parts got into a new section dedicated to bandwidth constraints (together with expectations around standard namespaces)

**Comment by SimonCropp** [comment]
@yvesgoeleven @ramonsmits should this branch be deleted?

**Comment by yvesgoeleven** [comment]
@SimonCropp yes, forgot to do that, sorry

**Comment by SimonCropp** [comment]
@yvesgoeleven thanks

**Pull request closed without merging**
