### PR TITLE
Replaced diagrams with updated versions in SVG

### PR DESCRIPTION
**Pull request by sergioc**
Replaced diagrams with updated versions in SVG

### CODE REVIEW

**Comment by DavidBoike** [comment]
@sergioc: On the [Lesson 2 diagram](https://github.com/Particular/docs.particular.net/blob/updated-nsb101-diagrams/tutorials/nservicebus-101/lesson-2/diagram.svg) the message's label should be `PlaceOrder`, not `ClientUI`.

**Comment by sergioc** [comment]
Thanks, fixed.

**Comment by DavidBoike** [comment]
@Particular/docs-maintainers There's no issue directly pointing markdown-specified images to SVG files, right?

**Comment by SimonCropp** [comment]
@DavidBoike no issue. in svg are much preferred

**Comment by DavidBoike** [comment]
@sergioc: Merged, and they work, but may not display exactly as you envisioned. Do you think any whitespace should be added around the diagrams to present them better within the gray outline?

* https://docs.particular.net/tutorials/nservicebus-101/
* https://docs.particular.net/tutorials/nservicebus-101/lesson-2/#exercise
* https://docs.particular.net/tutorials/nservicebus-101/lesson-3/#exercise
* https://docs.particular.net/tutorials/nservicebus-101/lesson-4/#exercise

**Comment by sergioc** [comment]
I'll handle it @DavidBoike

**Comment by sergioc** [comment]
White space issue addressed via https://github.com/Particular/DocsEngine/pull/293 and https://github.com/Particular/docs.particular.net/commit/5e5df5b37a7f2244c778a5a539253427a94a214e

**Pull request merged**
