### PR TITLE
Fix snippet

### PR DESCRIPTION
**Pull request by MarcinHoppe**

### CODE REVIEW

**Comment by SimonCropp** [comment]
that is actually intentional since the endpoint config would come after that

**Comment by MarcinHoppe** [comment]
The missing bracket looks like something is off. Maybe signal the missing code with an ellipsis or something?

**Comment by SimonCropp** [comment]
Yeah u r correct. It is dodgy. I will have a better look at it tomorrow

**Comment by MarcinHoppe** [comment]
Feel free to use this PR as a start 😄.

**Pull request merged**
