### PR TITLE
Tweak list of packages that don't support .NET core

### PR DESCRIPTION
**Pull request by bording**
FYI @Particular/dotnetcore-launch-squad

### CODE REVIEW

**Comment by bording** [comment]
What about the Azure host packages? This list currently implies that they'll be replaced by templates from `ParticularTemplates`, but that's not currently true.

@Particular/azure-maintainers What's the plan for these?

**Comment by SeanFeldman** [comment]
The are not replaced AFAIK, but deprecated.

**Comment by bording** [comment]
> The are not replaced AFAIK, but deprecated.

What does that mean? What's the alternative?

**Comment by SeanFeldman** [comment]
Customers will be able to upgrade from version 7 to version 8 (from NSB 6 to 7) with warning and error in version 9. Instead of Azure host, we're advising to switch to self hosting ([sample](https://docs.particular.net/samples/azure/self-host/?version=core_7)) in upgrade guide [here](https://docs.particular.net/nservicebus/upgrades/acs-host-7to8)

> The NServiceBus Azure Host will be deprecated as of Version 9 and users are recommended to switch to self hosting for new endpoints. Upgrading existing endpoints is still supported for Version 8.

For the [shared host](https://docs.particular.net/nservicebus/hosting/cloud-services-host/shared-hosting) we've concluded that it would be better to decouple from Azure, but nothing after that (https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/5).

**Comment by bording** [comment]
@SeanFeldman Instead of just having some code in the upgrade guide, is that something we should consider adding a template for?

**Comment by SeanFeldman** [comment]
Good question. @Particular/azure-maintainers thoughts?

**Comment by yvesgoeleven** [comment]
@bording @SeanFeldman what are these templates you are talking about? project templates?

**Comment by bording** [comment]
> @bording @SeanFeldman what are these templates you are talking about? project templates?

Yes, project templates that can be used via `dotnet new`: https://docs.particular.net/nservicebus/dotnet-templates

**Comment by DavidBoike** [comment]
Merged this, but I think the conversation about the Azure hosts should continue!

**Pull request merged**
