### PR TITLE
DataBus does not work with callbacks

### PR DESCRIPTION
**Pull request by ramonsmits**
Based on https://groups.google.com/forum/#!msg/particularsoftware/j5fKCILkD3o/qchIhaQWJAAJ

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/nservicebus-maintainers should we throw an exception in this scenario

**Comment by timbussmann** [comment]
> should we throw an exception in this scenario

not against that.

**Comment by andreasohlund** [comment]
:+1: to throw

**Comment by danielmarbach** [comment]
Can we lay out the why it doesn't work and why we don't want it to work?

And then when we agree on the reasoning implement the exception.

**Comment by DavidBoike** [comment]
How's this (added commit) for rationale on no databus in callbacks?

Although I think, perhaps, it should be moved to further down the page. "Hey this doesn't work with callbacks" is probably not the first thing we should be saying on the topic.

**Comment by indualagarsamy** [comment]
If we are going to throw an exception, do we need to document this as "Callbacks are not supported"? This seems more like a bug in the core that we should be fixing to me than something we should be documenting.

**Comment by mikeminutillo** [comment]
> If we are going to throw an exception, do we need to document this as "Callbacks are not supported"? This seems more like a bug in the core that we should be fixing to me than something we should be documenting.

:+1: We used to document other feature combos that didn't work (i.e. No Transactions with SLR) but we don't seem to do that anymore. Is that because we throw at runtime when we detect invalid combinations?

> Can we lay out the why it doesn't work and why we don't want it to work?

Is "why it doesn't work" just because of behavior ordering? 

If the [DataBus Receive Behavior](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DataBus/DataBusReceiveBehavior.cs) happens before the [Callbacks Receive Behavior](https://github.com/Particular/NServiceBus.Callbacks/blob/develop/src/NServiceBus.Callbacks/Reply/RequestResponseInvocationForMessagesBehavior.cs) wouldn't this work? They are both `Behavior<IIncomingLogicalMessageContext>` so the eventual order in the pipeline isn't deterministic is it?

**Comment by danielmarbach** [comment]
I think it would be pretty weak if the reasoning behind it is: technical reasons. We either have strong arguments why we don't want to support it or we don't. if we don't have strong arguments then I would expect it to work

**Comment by DavidBoike** [comment]
So do we want to try to support it then?

**Comment by timbussmann** [comment]
I agree with @danielmarbach , this should be handled as a bug. Let's close this PR then?

**Comment by danielmarbach** [comment]
@ramonsmits @DavidBoike I talked to @andreasohlund and we agreed it is a bug. Can you investigate the bug and see how much it takes to fix it? It might be an ordering issue of behaviors only.

(judging by the comments from @timbussmann he is on the same page as well)

**Comment by danielmarbach** [comment]
@SimonCropp let's close this PR

**Comment by danielmarbach** [comment]
Opened up a new issue https://github.com/Particular/NServiceBus.Callbacks/issues/29

**Pull request closed without merging**
