### PR TITLE
RabbitMQ add warning that messages can only be delayed for roughly 8.5

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by danielmarbach** [comment]
Why should this be a warning? The text is already clear enough what the limitations are. I don't see a reason to bug people with more yellow boxes.

**Comment by adamralph** [comment]
I don't think this should be a warning.

**Comment by ramonsmits** [comment]
What do you suggest then? I do want this limitation to be more prominent as I don't think the text is clear. Its a wall of text that nobody reads in detail.

**Comment by adamralph** [comment]
@ramonsmits `NOTE:`?

**Pull request merged**
