### PR TITLE
remove redundant pool size

### LINKED ISSUE #2878: Max/min Pool Size
we have a bunch of connection strings in snippets with `Max Pool Size` and `Main Pool Size` but with no explanation of why and what is the significance of the values

ping @Particular/sqlpersistence-maintainers @Particular/sqlserver-transport-maintainers thoughts

I was planning on just removing them all

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #2878

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
Doesn't it generate warnings on 3.0.x version of the transport?

**Comment by SimonCropp** [comment]
@MarcinHoppe yes i reverted after realizing that.

**Comment by MarcinHoppe** [comment]
BTW the `Min Pool Size` validation will go away in 3.1.

**Comment by SimonCropp** [comment]
So can the pool size be re removed in the 3.1 timeframe?

**Comment by SimonCropp** [comment]
ie removed from the samples

**Comment by MarcinHoppe** [comment]
I.e., remove the `Min Pool Size` from connection strings and leave `Max Pool Size` as we will still be validating it.

I created Particular/NServiceBus.SqlServer#371 and added it to the relevant milestone so that we don't miss it.

**Pull request merged**
