### PR TITLE
Remove reference into internal container implementation

### PR DESCRIPTION
**Pull request by bording**

### CODE REVIEW

**Comment by bording** [comment]
I could just simplify the whole thing and drop the reference to the internal container altogether.

**Comment by danielmarbach** [comment]
For me it would make sense but let's hear tim's opinion
-- 

Have you tried NServiceBus V6 <https://particular.net/nservicebus-v6> yet?

Learn how to scale applications with microservices and NServiceBus 6
<https://www.pluralsight.com/courses/microservices-nservicebus6-scaling-applications>
.
------------------------------

*Join Udi Dahan's next Advanced Distributed Design Course:*

September 2017 Los Angeles, CA, USA <http://particular.net/adsd>

November 2017 Sydney, Australia <http://particular.net/adsd>
------------------------------

**Comment by timbussmann** [comment]
> I could just simplify the whole thing and drop the reference to the internal container altogether.

👍

**Comment by SimonCropp** [comment]
happy to have the content dropped

**Comment by bording** [comment]
I've revised the commit to drop the reference to what we're using for the internal container.

**Pull request merged**
