### PR TITLE
remove NSBExtensions stuff from docs site

### PR DESCRIPTION
**Pull request by SimonCropp**
removes all https://github.com/NServiceBusExtensions stuff from docs

to remove the friction on both sides of keeping them up to date

as discussed with @andreasohlund .

i suspect this will break in a few ways. appreciate if those build errors can be copied into comments

### CODE REVIEW

**Comment by ramonsmits** [comment]
@SimonCropp ContentVerification (1):

- System.Exception : Could not find nuget for nugetId:NServiceBus.SqlServer.Native in 'components\core-dependencies'.

**Comment by andreasohlund** [comment]
Why did you remove samples that didn't use the NSBExtensions?

Eg samples/web/sql-http-passthrough/SqlHttpPassthrough_4/Tests/Tests.csproj

**Comment by andreasohlund** [comment]
Ah, I missed that it used     

<PackageReference Include="NServiceBus.Attachments.Sql" Version="1.*" />

**Comment by bording** [comment]
@SimonCropp Currently failing with:
```
System.Exception : Could not find component for key:DataAnnotations
   at MetaDataJoiner.GetComponent(String componentKey) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Component\MetaDataJoiner.cs:line 80
   at AllPagesReader.CreatePage(PageHeader header, String relativePath, String url, String originalPath, PageType pageType) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 138
   at AllPagesReader.ProcessIndex(String directory, Page parent) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 133
   at AllPagesReader.ProcessDirectory(String directory, Page parent, List`1 errors) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 97
   at AllPagesReader.ProcessDirectories(String directory, Page parent, List`1 errors, Deserializer deserializer) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 70
   at AllPagesReader.ProcessDirectory(String directory, Page parent, List`1 errors) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 99
   at AllPagesReader.ProcessRootDirectories(String directory, Page parent, List`1 errors) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 55
   at AllPagesReader.Start() in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\Reading\AllPagesReader.cs:line 41
   at SiteRunner.RenderSite(String sourceDirectory, String targetDirectory, String lastShaPrefix) in C:\BuildAgent\work\ca82fba321bd227a\src\ParticularDocsCore\SiteRunner.cs:line 31
   at ContentVerificationTest.RunFullSiteGeneration() in C:\BuildAgent\work\ca82fba321bd227a\src\DocsWeb.Tests\ContentVerificationTest.cs:line 24
```

**Comment by SimonCropp** [comment]
and next?

**Comment by DavidBoike** [comment]
Same exception for `key:NewtonsoftEncryption`

**Comment by DavidBoike** [comment]
key:SqlTransportNative

**Comment by DavidBoike** [comment]
System.AggregateException : One or more errors occurred.
  ----> System.Exception : Could not render page: C:\BuildAgent\work\a48e3341ae42e493\samples\pipeline\audit-filtering\sample.md
  ----> System.Exception : Could not find referenced samples/audit-filter when rendering page /samples/pipeline/audit-filtering/.

**Comment by SimonCropp** [comment]
next?

**Comment by DavidBoike** [comment]
Could not render page: C:\BuildAgent\work\a48e3341ae42e493\samples\serializers\newtonsoft\sample.md
  ----> System.Exception : Could not find referenced samples/encryption/newtonsoft-json-encryption when rendering page /samples/serializers/newtonsoft/.

**Comment by SimonCropp** [comment]
next?

**Comment by bording** [comment]
image

The solution files still have references to projects that you've deleted.

**Comment by SimonCropp** [comment]
ok. ready to merge

**Comment by SimonCropp** [comment]
bump

**Pull request merged**
