### PR TITLE
[WIP]Satellites no longer have a pipeline

### PR DESCRIPTION
**Pull request by andreasohlund**
https://github.com/Particular/NServiceBus/pull/3797 needs to be merged before this one

### CODE REVIEW

**Comment by SimonCropp** [comment]
needs a rebase

**Comment by weralabaj** [comment]
rebased

**Comment by weralabaj** [comment]
Three snippets are missing, either I messed up rebase or we need to add them. I'll check with Andreas tomorrow.

**Comment by weralabaj** [comment]
From Andreas: waiting with the three snippets for changes in core, plans to get it done by the end of this week. Let's wait with the merge.

**Comment by indualagarsamy** [comment]
@weralabaj - any updates on this?

**Comment by tmasternak** [comment]
This needs to wait until https://github.com/Particular/V6Launch/issues/69 is done. It changes the satellite seam even further (enabling passing recoverability configuration).

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Particular/docs.particular.net/commit/935eafa5a3dadd3f2bfa206d2d0bd413c9f27211

**Pull request closed without merging**
