### PR TITLE
Adding note about deprecating ConfigureTransport

### PR DESCRIPTION
**Pull request by hmemcpy**
Added this in the upgrade guide. Please see #1177 if anything else should be added.

### CODE REVIEW

**Comment by SimonCropp** [comment]
That sample does not show how to transition from one to the other so it is not sufficient as it stands

**Comment by SimonCropp** [comment]
@hmemcpy any thoughts on this?

**Comment by hmemcpy** [comment]
@SimonCropp well, we didn't have any doco/sample on the previous API, I thought to add this to the upgrade guide in case any of the downstreams use the old class. Do you think we should provide a sample for v5 as well?

**Comment by SimonCropp** [comment]
i am calling doco bankruptcy on the old transport doco and merging this

**Pull request merged**
