### PR TITLE
Add documentation on how to inject the raven session

### PR DESCRIPTION
**Pull request by lailabougria**
- [x] Point the 6.5 snippet to Myget/nuget version

### CODE REVIEW

**Comment by kbaley** [comment]
Is there supposed to be a markdown file to go with this?

**Comment by lailabougria** [comment]
@kbaley No these are snippets, so I'm just adding the snippets that reference the new version, otherwise, the docs engine will be unable to resolve the snippet for the version that we introduce.

**Review by mauroservienti — APPROVED** [review]
Does it make sense to craft a sample for this new behavior?

**Comment by lailabougria** [comment]
Personally, I don't think so @mauroservienti . We have the snippets showing how you can inject the session, there's not much more to show than that, so I'm failing to see how a sample adds value in this case.

**Review by kbaley — APPROVED** [review]

**Review by mauroservienti — APPROVED** [review]

**Pull request merged**
