### PR TITLE
Switch owner of SQS

### PR DESCRIPTION
**Pull request by danielmarbach**
DO NOT MERGE YET

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/aws-maintainers please review

**Comment by SimonCropp** [comment]
From the perspective of docs this will result in sqs rendering as "fully supported by particular with no caveats". Has that been decided on?

**Comment by danielmarbach** [comment]
Call will take place next week. I'll add do not merge yet

**Comment by SimonCropp** [comment]
so decision made. do we merge?

**Comment by mauroservienti** [comment]
Yes. Go.

**Pull request merged**
