### PR TITLE
Updating host profile doco to reflect host v7

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/docs-maintainers need some help to figure out how to best split the info into v6/v7 sections since v7 differs quite a bit

**Comment by weralabaj** [comment]
@andreasohlund use partials? they can cover even a few sections of the article, e.g. see https://docs.particular.net/nservicebus/scalability-and-ha/scale-out and how partials for v5 and v6 look like

**Comment by andreasohlund** [comment]
@weralabaj page is now using partials. Can you give this a once over to see that I'm on the right track?

**Comment by weralabaj** [comment]
@andreasohlund you missed one part of the partial files name - component :) fixed now, I'm reviewing content :)

**Pull request merged**
