### PR TITLE
HttpDefaultConnectionLimit setting

### PR DESCRIPTION
**Pull request by SeanFeldman**
Doco for `ServiceControl/HttpDefaultConnectionLimit` to document PR https://github.com/Particular/ServiceControl/pull/527

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/servicecontrol please review

**Comment by johnsimons** [comment]
@SeanFeldman you need to mention that this setting is only available from 1.7

**Comment by SeanFeldman** [comment]
@johnsimons, feels odd to release doco saying "from 1.7" when 1.7 is not out yet.

**Comment by SimonCropp** [comment]
@SeanFeldman might feel weird. but documenting into the future does make the doco simpler to write and manage

**Comment by johnsimons** [comment]
Then don't merge it yet :wink:

**Comment by SeanFeldman** [comment]
@SimonCropp added version info.
Should we review how this kind of info is added?

**Comment by SimonCropp** [comment]
So r we leaving this open? should it be prefixed with WIP do no one accidentally merges it?

**Comment by SeanFeldman** [comment]
From work perspective - nothing's left, it's done.
If we're ok with publishing doco that makes a reference for future version, then can be merged @SimonCropp

**Comment by gbiellem** [comment]
I've changed the title and made it WIP.  I think that's safer

**Comment by SimonCropp** [comment]
@gbiellem i already merged this

**Comment by gbiellem** [comment]
I just noticed it's already merged - forget I said anything

**Pull request merged**
