### PR TITLE
WIP: wormhole to nsb v7

### PR DESCRIPTION
**Pull request by SimonCropp**
WIP until there is a beta nuget

### CODE REVIEW

**Comment by SimonCropp** [comment]
@SzymonPobiega need any help with wormhole changes

**Comment by SzymonPobiega** [comment]
@SimonCropp , nah, I am fine. I had to migrate the projects over to the new format which took me a while. Should be ready by the end of the weekend.

**Comment by SimonCropp** [comment]
this will need a rebase

**Comment by SzymonPobiega** [comment]
Thanks @SimonCropp ❤️

**Pull request merged**
