### PR TITLE
[WIP] SC V2.0 changes

### PR DESCRIPTION
**Pull request by gbiellem**
Installation and config changes for SC 2.0 ( Raven 3 update)

Relates to https://github.com/Particular/ServiceControl/pull/772
Rleates to https://github.com/Particular/PlatformDevelopment/issues/887

### CODE REVIEW

**Comment by indualagarsamy** [comment]
@gbiellem - is this good for review or still WIP?

**Comment by SimonCropp** [comment]
@mikeminutillo @boblangley @johnsimons can one of you take this over? since greg is on leave

**Comment by mikeminutillo** [comment]
@SimonCropp I will take a look. The 2.0 SC isn't ready to go yet so this can't go out anyway

**Comment by gbiellem** [comment]
Since this upgrade has been called off this PR is no longer required

**Pull request closed without merging**
