### PR TITLE
Raven custom saga finder

### PR DESCRIPTION
**Pull request by danielmarbach**
* Simplified to only have one executable
* Added SagaNotFoundHandler in case people are trying this against their own RavenDB instance and forget to install the server side of the UniqueConstraints bundle
* Updated doco accordingly

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/documentation please review

**Comment by danielmarbach** [comment]
@SimonCropp good changes. merge?

**Comment by SimonCropp** [comment]
was wondering if we are spinning up an embedded store why not just pass that into the NSB.RavenDB. no need to go via http???

**Comment by danielmarbach** [comment]
I asked myself that as well. But if we do it like it is now you better see in the sample how a custom store needs to register the client listener

**Comment by SimonCropp** [comment]
i think here we are trying to illustrate custom saga finding. so the least moving pieces in all other areas is a win

**Comment by danielmarbach** [comment]
Fair. I’ll change



*From:* Simon Cropp [mailto:notifications@github.com]
*Sent:* Donnerstag, 11. Juni 2015 14:09
*To:* Particular/docs.particular.net
*Cc:* Daniel Marbach
*Subject:* Re: [docs.particular.net] Raven custom saga finder (#655)



i think here we are trying to illustrate custom saga finding. so the least
moving pieces in all other areas is a win

—
Reply to this email directly or view it on GitHub
<https://github.com/Particular/docs.particular.net/pull/655#issuecomment-111109650>
.

**Comment by danielmarbach** [comment]
@SimonCropp pushed the change. I slightly changed the doco as well and moved the region to only include the necessary stuff in the snippet

**Comment by SimonCropp** [comment]
looks good. merging

**Pull request merged**
