### PR TITLE
updates to assembly scanning doco for v6

### PR DESCRIPTION
**Pull request by SeanFeldman**
Have ended up breaking examples into several groups:
- Exclusion
- Inclusion
- Deprecated from V6

@Particular/documentation please review

### CODE REVIEW

**Comment by SimonCropp** [comment]
@johnsimons since u wrote most of this functionality can u review this

**Comment by johnsimons** [comment]
Sorry guys, forgot about this one.

It may be worth mentioning that the assembly scanning configuration options need to be specified at `IConfigureThisEndpoint` or when `BusConfiguration` is instantiated in self hosting, in other words, these options do not work if specified in `INeedInitialization`.

**Comment by SeanFeldman** [comment]
Thank you @johnsimons , good point. Added that.
Please review.

**Comment by SeanFeldman** [comment]
Very good point, and sadly misleading API since other things (like endpoint name) can be changed during `INeedInitialization` execution :( I have added a note @johnsimons , thank you.
Is it good to be merged?

**Comment by SeanFeldman** [comment]
@johnsimons good to merge?

**Comment by johnsimons** [comment]
I think it look alright

**Comment by SeanFeldman** [comment]
Merged manually

**Pull request closed without merging**
