### PR TITLE
[WIP] ASQ aliases moved to a separate page

### PR DESCRIPTION
**Pull request by Scooletz**
Connects to #1865

This PR extracts aliases for multiple accounts to a separate `aliases.include.md`. The include is used in the scale out page as well as in the newly created separate page for aliases. 

My personal doubt: this menu item unfortunately is visible for all versions of NSB as there's no menu versioning. I can't provide a general article as this page describes a feature that has been introduced in the ASQ 7.

### CODE REVIEW

**Comment by Scooletz** [comment]
Could you take a look @SeanFeldman ? 
I'm raising my doubt in this PR description `This unfortunately is visible for all versions of NSB as there's no menu versioning.`

**Comment by weralabaj** [comment]
ping @SimonCropp thoughts on this approach?

**Comment by SeanFeldman** [comment]
This is not the only page that is targeting vNext and will show up on the menu. And at the same time, vNext will become shortly vCurrent.

@weralabaj this: https://github.com/Particular/docs.particular.net/pull/1926#issuecomment-248976184

**Comment by weralabaj** [comment]
But in Google group you can always link to paragraph, and we do that quite often in fact.

@SimonCropp thoughts?

**Comment by SimonCropp** [comment]
i dont mind splitting a page out if the topic is deep/complex enough to justify its own page

but i dont like including the same large body of the include in multiple locations. why not link to the new page?

**Comment by Scooletz** [comment]
@SimonCropp Do I understand you correctly:
1. move the body to the new page which is included in the menu
1. put a link in the original page navigating to the newly created
1. remove the include
?

**Comment by SimonCropp** [comment]
@Scooletz yes

**Comment by SimonCropp** [comment]
@Scooletz note that i said above though

> i dont mind splitting a page out if the topic is deep/complex enough to justify its own page

i prefer to only split out pages when is absolutely clear that is it necessary.

**Comment by Scooletz** [comment]
@SeanFeldman could you chime in?

**Comment by SeanFeldman** [comment]
I think we're discussing this for way too long. My point on this has not changed, if customers don't know what to do and can't [easily locate the feature at the doco site](https://groups.google.com/forum/#!topic/particularsoftware/ANBSuy69oLw) then I'd like to see it listed out just like we've [done for ASB](https://docs.particular.net/nservicebus/azure-service-bus/securing-connection-strings). Saying that, if people disagree, well, this is what democracy is for :wink:

**Comment by Scooletz** [comment]
I'm closing this without merging as no consensus has been reached.

**Pull request closed without merging**
