### PR TITLE
[WIP] Guidance on configuring cleanup interval

### PR DESCRIPTION
**Pull request by ramonsmits**
Guidance on configuring outbox in regards to the cleanup interval and deduplication time window.

Partially based on response by @janovesk  here https://groups.google.com/forum/#!searchin/particularsoftware/TimeToKeepDeduplicationData/particularsoftware/RRig2_y6S48/A7ctrIp0AwAJ

### CODE REVIEW

**Comment by mikeminutillo** [comment]
As the content presented here is based on a mailing list post, it has quite a bit of personal voice and is very conversational in nature. We have been working actively in doco to remove these traits from our content. 

For example:

Instead of 
> If your endpoint processes a high volume of message per second it might be needed to change this interval to run more frequently.
>
> If your endpoint processes 1,000 message per second the default value would mean that every minute 60,000 outbox records or documents will be deleted. In that case it probably makes more sense to set the interval to every second to delete 1,000 records per second or even more often like every 100 milli seconds to delete on average 100 records at each interval.

I would say
> An endpoint that processes a high volume of messages per second requires a shorter interval to clean up more frequently.
>
> For example, an endpoint that processes 1,000 messages per second generates 60,000 outbox records per minute. In that case, running the cleanup task every second would result in deleting 1,000 records each interval. Running the cleanup task every 100 milliseconds reduces this number to 100 records each run.

 @ramonsmits are you happy to try and remove words like "you" and "your" from this content?

**Comment by ramonsmits** [comment]
Thanks @mikeminutillo , I've rewritten it. Is this better?

**Comment by weralabaj** [comment]
> For example, an endpoint that processes 1,000 messages per second generates 60,000 outbox records per minute. In that case, running the cleanup task every second would result in deleting 1,000 records at each 1 second interval. Running the cleanup task every 100 milliseconds reduces this number to 100 records per each run.

Is 1000 msgs deleted at once too big number? Mentioning it in the example makes it seem so.

Snippet showing how to change this setting would make sense here.

> In such case the deduplication time window could be set to expire immediately.

That should be followed by a snippet that shows how to do that. But do we really want to encourage people to do that?

> Outbox records will only be removed when all the transport operations succeeded

How about "when all the operations succeeded" or "when message was processed successfully".

> Server failure/Network failure/OPS Detect, asses and fix period

I don't understand what you're getting at in those sections. Is there some config setting to control that? or is it more like "Things you should consider before deployment"?

What is "OPS"?

> there is always the possibility to *increase* the deduplication window on the receivers to create more time to come up with a fix.

Again, show how. That seems like a "Troubleshooting/Recovery" section?

> A large set of deduplication records might need to be deleted when reverting the deduplication time window to the old value.

Again, that's "Troubleshooting" not standard configuration topic.

**Comment by weralabaj** [comment]
I think we need to move some of this content to a separate section or article, something like what we've done for ServiceControl here http://docs.particular.net/servicecontrol/servicecontrol-in-practice.

So one part could be configuration - what settings are available, what they mean, how to adjust them (snippets) and how to find good values. Then troubleshooting/recovery guide which covers the rest, but we'd need some intro to provide some link (like in the ServiceControl article), right now it's a bit confusing.

**Comment by SimonCropp** [comment]
@ramonsmits r u still working on this? Should it be handed to someone else? Or should it be abandoned?

**Pull request closed without merging**
