### PR TITLE
List DTC support as advantage

### PR DESCRIPTION
**Pull request by timbussmann**
shouldn't we include this on the advantages?

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
I would also add that when combined with NHibernate persistence, we can support lightweight distributed transactions without relying on the DTC.

**Comment by timbussmann** [comment]
@MarcinHoppe since I don't explicitly mention DTC, I'd say this is going to deep?

**Comment by MarcinHoppe** [comment]
I'd err on the side of spelling out the benefits explicitly, if possible.

**Comment by SimonCropp** [comment]
@MarcinHoppe 

> I'd err on the side of spelling out the benefits explicitly, if possible.

i gave the link to the official doco for MSDTC. i think it is MSs job to "sell DTC" as a good thing

**Pull request merged**
