### PR TITLE
Simplified NumberOfRetries method a bit

### PR DESCRIPTION
**Pull request by Aetherix**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Aetherix i am not certain this change makes it any simpler. it also loses some of the intent. since the before snippet shows that the `int.tryparse` does not need to be called if the header does not exist

**Comment by Aetherix** [comment]
Thank you Simon for the review. Very much appreciated. Does this also mean that I can assume that if the 'retries' header exists, it will always contain a valid number and never "" or null?

**Comment by SimonCropp** [comment]
>  I can assume that if the 'retries' header exists, it will always contain a valid number and never "" or null?

yes this is correct

**Comment by SimonCropp** [comment]
@Aetherix i added a note to clarify that https://docs.particular.net/nservicebus/messaging/headers#retries-handling-headers

Closing this. please raise a new PR if u think it needs more clarification. 

And thanks for contributing

**Pull request closed without merging**
