### PR TITLE
a vs an

### PR DESCRIPTION
**Pull request by bbrandt**
http://www.englishpage.com/articles/a-vs-an.htm

### CODE REVIEW

**Comment by SimonCropp** [comment]
@bbrandt  thanks for the quick PRs :)  I was actually look at a leader board of community contributors and your name showed up. So thanks heaps

**Comment by bbrandt** [comment]
Thanks for merging.  Glad to help.  Is that leader board publicly accessible so I can brag to all my nerd friends?



On Tue, Jun 21, 2016 at 5:18 PM -0500, "Simon Cropp" <notifications@github.com<mailto:notifications@github.com>> wrote:


@bbrandt<https://github.com/bbrandt> thanks for the quick PRs :) I was actually look at a leader board of community contributors and your name showed up. So thanks heaps

-

**Comment by SimonCropp** [comment]
>  Is that leader board publicly accessible 

Not as yet. I have contemplated putting it online a few times. do u think it would be useful/fun/valuable?

**Comment by bbrandt** [comment]
I think it'd be a fun thing to tweet about.
I've never read of a situation where gamification produced a negative result.



On Tue, Jun 21, 2016 at 6:37 PM -0500, "Simon Cropp" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is that leader board publicly accessible

Not as yet. I have contemplated putting it online a few times. do u think it would be useful/fun/valuable?

-

**Pull request merged**
