### PR TITLE
Queue creation

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/NServiceBus/pull/3080

@Particular/documentation please review

### CODE REVIEW

**Comment by SimonCropp** [comment]
how si this related to this PR https://github.com/Particular/docs.particular.net/pull/807  ?

**Comment by SimonCropp** [comment]
@SzymonPobiega can u sync with @danielmarbach on this one?

**Comment by danielmarbach** [comment]
@SimonCropp I don't think it makes sense to bundle the two PRs. This one is about the upgrade guide on `IWantToCreateQueues` and [@SzymonPobiega's PR](https://github.com/Particular/docs.particular.net/pull/807) is about `QueueBinding` and hopefully queue creation. We can merge this one and add the link to the upgrade guide when https://github.com/Particular/docs.particular.net/pull/807 is done.

**Comment by SimonCropp** [comment]
@danielmarbach my point is the other pr also adds a similar note in the upgrade guide so they clearly conflict. i am not asking you to "bundle the two PRs". just instead to talk to @SzymonPobiega since this PR was clearly done without knowledge of the other

**Comment by danielmarbach** [comment]
@simoncropp I'll do. But nothing is stopping us to pull this in, right?

**Pull request merged**
