### PR TITLE
Propose new SC menu structure

### PR DESCRIPTION
**Pull request by mikeminutillo**
Implements the structure defined in https://github.com/Particular/docs.particular.net/issues/2935#issuecomment-313579404

### CODE REVIEW

**Comment by mikeminutillo** [comment]
@Particular/servicecontrol-maintainers please take a look and see if you're happy for me to merge this. We can improve the content and add some index/landing pages to reflect this content later if we need to.

**Comment by mikeminutillo** [comment]
If you want to visualize it, it looks like this:

- ServiceControl
  - ServiceControl instances
    - Planning
      - [Capacity Planning](https://docs.particular.net/servicecontrol/capacity-and-planning)
      - [Optimizing use in different environments](https://docs.particular.net/servicecontrol/servicecontrol-in-practice)
      - [Security](https://docs.particular.net/servicecontrol/securing-servicecontrol)
      - [Non-Priveleged Accounts](https://docs.particular.net/servicecontrol/configure-non-privileged-service-account)
    - [Installation](https://docs.particular.net/servicecontrol/installation)
      - [Installing Silently](https://docs.particular.net/servicecontrol/installation-silent)
      - [Managing via PowerShell](https://docs.particular.net/servicecontrol/installation-powershell)
      - [Cluster Deployment](https://docs.particular.net/servicecontrol/deploying-servicecontrol-in-a-cluster)
      - [Licensing](https://docs.particular.net/servicecontrol/license)
      - [Settings](https://docs.particular.net/servicecontrol/creating-config-file)
      - [Overriding the host identifier](https://docs.particular.net/nservicebus/hosting/override-hostid)
      - [RavenDB Location](https://docs.particular.net/servicecontrol/configure-ravendb-location)
      - [Configure the URI](https://docs.particular.net/servicecontrol/setting-custom-hostname)
      - [Logging](https://docs.particular.net/servicecontrol/logging)
      - [Forwarding Queues](https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior)
      - [Configuring MSMQ](https://docs.particular.net/servicecontrol/configuring-msmq)
    - Management
      - [Data Expiration](https://docs.particular.net/servicecontrol/how-purge-expired-data)
      - [Backup](https://docs.particular.net/servicecontrol/backup-sc-database)
      - [Compacting database](https://docs.particular.net/servicecontrol/db-compaction)
    - [Troubleshooting](https://docs.particular.net/servicecontrol/troubleshooting)
      - [Expose internal database](https://docs.particular.net/servicecontrol/use-ravendb-studio)
  - Integration
    - [Plugins](https://docs.particular.net/servicecontrol/plugins)
      - [Heartbeats](https://docs.particular.net/servicecontrol/plugins/heartbeat)
      - [Custom checks](https://docs.particular.net/servicecontrol/plugins/custom-checks)
      - [Saga audits](https://docs.particular.net/servicecontrol/plugins/saga-audit)
    - [Integration events](https://docs.particular.net/servicecontrol/contracts)
    - [Transport adapter](https://docs.particular.net/servicecontrol/transport-adapter)
      - [Incompatible transport features](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features)
      - [dotnet new Template](https://docs.particular.net/servicecontrol/transport-adapter/template)

**Comment by mikeminutillo** [comment]
All of the entries under Installation after Settings, should be nested under Settings but that's one level too deep. We could pull a separate section for Configuration in between Installation and Management which would let us fix that.

**Comment by mikeminutillo** [comment]
Updated to fill in some gaps. Now it looks like this:

- [ServiceControl](https://docs.particular.net/servicecontrol/)
  - [ServiceControl instances](https://docs.particular.net/servicecontrol/servicecontrol-instances)
    - [Planning](https://docs.particular.net/servicecontrol/servicecontrol-in-practice)
      - [Capacity Planning](https://docs.particular.net/servicecontrol/capacity-and-planning)
      - [Security](https://docs.particular.net/servicecontrol/securing-servicecontrol)
      - [Non-Priveleged Accounts](https://docs.particular.net/servicecontrol/configure-non-privileged-service-account)
    - [Installation](https://docs.particular.net/servicecontrol/installation)
      - [Installing Silently](https://docs.particular.net/servicecontrol/installation-silent)
      - [Managing via PowerShell](https://docs.particular.net/servicecontrol/installation-powershell)
      - [Cluster Deployment](https://docs.particular.net/servicecontrol/deploying-servicecontrol-in-a-cluster)
      - [Licensing](https://docs.particular.net/servicecontrol/license)
      - [Settings](https://docs.particular.net/servicecontrol/creating-config-file)
      - [Overriding the host identifier](https://docs.particular.net/nservicebus/hosting/override-hostid)
      - [RavenDB Location](https://docs.particular.net/servicecontrol/configure-ravendb-location)
      - [Configure the URI](https://docs.particular.net/servicecontrol/setting-custom-hostname)
      - [Logging](https://docs.particular.net/servicecontrol/logging)
      - [Forwarding Queues](https://docs.particular.net/servicecontrol/errorlog-auditlog-behavior)
      - [Configuring MSMQ](https://docs.particular.net/servicecontrol/configuring-msmq)
    - Management
      - [Data Expiration](https://docs.particular.net/servicecontrol/how-purge-expired-data)
      - [Backup](https://docs.particular.net/servicecontrol/backup-sc-database)
      - [Compacting database](https://docs.particular.net/servicecontrol/db-compaction)
    - [Troubleshooting](https://docs.particular.net/servicecontrol/troubleshooting)
      - [Expose internal database](https://docs.particular.net/servicecontrol/use-ravendb-studio)
  - [Integration](https://docs.particular.net/servicecontrol/integration)
    - [Plugins](https://docs.particular.net/servicecontrol/plugins)
      - [Heartbeats](https://docs.particular.net/servicecontrol/plugins/heartbeat)
      - [Custom checks](https://docs.particular.net/servicecontrol/plugins/custom-checks)
      - [Saga audits](https://docs.particular.net/servicecontrol/plugins/saga-audit)
    - [Integration events](https://docs.particular.net/servicecontrol/contracts)
    - [Transport adapter](https://docs.particular.net/servicecontrol/transport-adapter)
      - [Incompatible transport features](https://docs.particular.net/servicecontrol/transport-adapter/incompatible-features)
      - [dotnet new Template](https://docs.particular.net/servicecontrol/transport-adapter/template)

**Comment by mikeminutillo** [comment]
@Particular/docs-maintainers in your opinion, should I move the content around to match the above layout as a part of this PR? Should I wait and do it as another PR once the layout has had a chance to settle in?

**Comment by SzymonPobiega** [comment]
👍 to wait for it to settle in a bit.

**Comment by mikeminutillo** [comment]
OK. Then I think this is ready to merge. Then I can start to add in the Monitoring instance doco as two new PRs. One will be all new content that will not be added to the menu. The second will add the first to the menu and update the existing pages to refer to Monitoring instances.

**Comment by weralabaj** [comment]
@mikeminutillo when raising new PRs, please link to this one, so it's easier to follow. Thanks!

**Pull request merged**
