### PR TITLE
Update home.md

### PR DESCRIPTION
**Pull request by sergioc**
Modified html to allow for a 2x2 layout for products + SC

Need to add servicecontrol.png (https://www.dropbox.com/s/aewg6y73ilve106/serviceControl.png?dl=0) + change links.

### CODE REVIEW

**Comment by sergioc** [comment]
@SimonCropp is there a way for us to preview this?

**Comment by SimonCropp** [comment]
not really. but if you have modified the html in the same way as you have on your local copy it should not be necessary.

but it is trivial to roll back or tweak if something is wrong

**Comment by sergioc** [comment]
I suggest we pull this while we're both online, so that we can quickly roll
back.

Still need to add the right SC links and image, though.

Sergio

**Comment by SimonCropp** [comment]
closing this since it is out of date and will need to be re-done

**Pull request closed without merging**
