### PR TITLE
lucidchart update

### PR DESCRIPTION
**Pull request by SeanFeldman**
Capture how generated images could be maintained.

@Particular/docs-maintainers please review

### CODE REVIEW

**Comment by weralabaj** [comment]
@SeanFeldman question - since that is public readme is there anything we could ask for when people outside the company contribute? (any source files, exports...) If not then it's ok, I don't think it'll happen very often.

Could we make an announcement and add in it info on how to get a license? Do we have a shared account for this?

**Comment by SeanFeldman** [comment]
@weralabaj I've never seen anyone external contributing anything other than textual content. We can deal with that when it happens.

**Comment by SimonCropp** [comment]
@SeanFeldman can we deep link into lucid chart? so we dont need to copy images over?

**Comment by SimonCropp** [comment]
then if we deep link we could set this up http://support.blakeschool.org/entries/23015117-Automatic-Synchronization-from-LucidChart-To-Google-Drive

**Comment by SeanFeldman** [comment]
Who needs images. ASCII FTW!
[EndpointOrientedTopology.png.txt](https://github.com/Particular/docs.particular.net/files/227152/EndpointOrientedTopology.png.txt)

**Comment by SeanFeldman** [comment]
@SimonCropp not sure how deep linking would help us. The images would be still generated manually. Also, having content spread across 2 sources will complicate things. I might be wrong though :)

**Comment by SimonCropp** [comment]
was thinking if  lucid chart has a deep link standard to an image the update process would be just edit on their web app. no export needed

**Comment by SeanFeldman** [comment]
Unfortunately, images need to be exported manually. Go ASCII :P

**Comment by weralabaj** [comment]
Ok so the last question , do we need to ping Sam to get more licenses https://github.com/Particular/Collaboration/issues/392? Or could we have one shared for docs?

**Comment by SeanFeldman** [comment]
@weralabaj it depends on what @SimonCropp has discovered with deep linking. I saw him hitting lucidchart URLs directly to generate images w/o exporting images explicitly. If that works and and rendering is to what we need, we might rethink the approach (and PR).

**Comment by weralabaj** [comment]
@SimonCropp given deep linking investigation is there anything you'd like to change here? or can I merge as is?

**Comment by SimonCropp** [comment]
merge as is. deep linking can happen later as a second step

**Pull request merged**
