### PR TITLE
Fix casing in msmq routing file snippet

### PR DESCRIPTION
**Pull request by andreasohlund**
@timbussmann @SzymonPobiega should we consider making the comparison case insensetive to avoid issues with casing? (see https://groups.google.com/d/msgid/particularsoftware/a3312514-c2bf-4f5c-aa6e-d9f988441f41%40googlegroups.com?utm_medium=email&utm_source=footer)

### CODE REVIEW

**Comment by indualagarsamy** [comment]
@andreasohlund - for the case comparison, can you open a new issue? I figured, since this is incorrect and you fixed it, it might be better to get this merged first.

**Comment by andreasohlund** [comment]
Will do after I sync with @timbussman

**Comment by indualagarsamy** [comment]
Awesome, thanks.

**Comment by timbussmann** [comment]
> @timbussmann @SzymonPobiega should we consider making the comparison case insensetive to avoid issues with casing

+ 💯

**Comment by andreasohlund** [comment]
@indualagarsamy issue raised https://github.com/Particular/NServiceBus/issues/4154

**Pull request merged**
