### PR TITLE
Removed failure detection

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Fixes https://github.com/Particular/docs.particular.net/issues/2352

### CODE REVIEW

**Comment by weralabaj** [comment]
smart @SzymonPobiega ;)

**Comment by SzymonPobiega** [comment]
@weralabaj the best code is deleted code. It contains no bugs :-)

**Comment by weralabaj** [comment]
ok i'll smoke test and merge

**Comment by weralabaj** [comment]
@SzymonPobiega do we also need to remove this fragment?

> This information is updated every time the automatic routing feature detects a change in the topology:

After restarting one of the sales processes the other is not really picking up the change. Or do we need to clarify something here?

**Comment by SzymonPobiega** [comment]
@weralabaj I've smoke tested it and works. When I kill `Sales2` the client continue to send every second messages to `Sales2` queue (because the automatic failure detection has been removed). Then when I start it back, it processes all the queued up messages and normally processes the new coming messages.

**Pull request merged**
