### PR TITLE
[WIP] Updated to new dynamic-less routing extensibility APIs

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Relates to https://github.com/Particular/NServiceBus/pull/4041

### CODE REVIEW

**Comment by weralabaj** [comment]
@SzymonPobiega can I close this PR given taht I merged the update to beta 7 one?

**Comment by SzymonPobiega** [comment]
@weralabaj nope. This one is the next to be applied when re release new internal beta.

**Comment by weralabaj** [comment]
Then would it make sense to re-create it against master? Unless that will be soon ;)

**Comment by SzymonPobiega** [comment]
@weralabaj yeah. That's why it is WIP. I don't want to forget about it ;-)

**Comment by SzymonPobiega** [comment]
This has already been addressed as part of other routing PRs. Closing.

**Pull request closed without merging**
