### PR TITLE
Updated the PrefetchCount default value

### PR DESCRIPTION
**Pull request by HEskandari**
The default value in the config doco is wrong according to https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Config/DefaultConfigurationValues.cs#L52.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@HEskandari thank you for the PR. It's accurate and correct. If you don't mind, I'd like to figure out first why it's not what the doco says before we merge.

**Comment by yvesgoeleven** [comment]
some guy called @SeanFeldman is to blame here ;) https://github.com/Particular/NServiceBus.AzureServiceBus/commit/fc09523078ae9fa2aa98c71afbb41c907cd75949

I assume we changed this after seeing people struggle with message lock lost exceptions, we downscaled the defaults quite a lot here

**Comment by weralabaj** [comment]
@SeanFeldman I marked this as a WIP, once you solve the mystery feel free to hit the merge button.

**Comment by SeanFeldman** [comment]
Thank you Hadi.

**Pull request merged**
