### PR TITLE
apply async practices

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@danielmarbach review please

**Comment by danielmarbach** [comment]
@SimonCropp these changes don't make sense. The APIs used return a string as a return type. The sample shows how to wrap APIs with return types. With your changes you'd just ignore the return type. I propose to close this

**Comment by SimonCropp** [comment]
@danielmarbach ahhh i get it. so i agree with u for HandlerWhichIntegratesWithRemotingWithAPM and will fix that. how about the other two?

**Comment by danielmarbach** [comment]
Look closer. They also are calling APIs with return types

**Pull request closed without merging**
