### PR TITLE
Updated NH references to 7.2

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/nhibernate-persistence-maintainers please review.

**Comment by SimonCropp** [comment]
what are the new features?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega Only version bumps as far as I can tell?

**Comment by SzymonPobiega** [comment]
@SimonCropp Unit of work. This is required for this sample: https://github.com/Particular/docs.particular.net/pull/2457

**Comment by SzymonPobiega** [comment]
@MarcinHoppe can you hit the green button?

**Pull request merged**
