### PR TITLE
removed duplicate text

### PR DESCRIPTION
**Pull request by dbelcham**
@Particular/documentation @SimonCropp 

First change so went conservative and created a PR. There appeared to be a duplicate section at the end of this document so I just deleted it.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Is the snippet no longer required?

**Comment by dbelcham** [comment]
The snippet is still being used. Both the text and the snippet were duplicated.

**Comment by SimonCropp** [comment]
Looking at the diff that is not the case.

**Comment by dbelcham** [comment]
For some reason the Source Diff is showing line 63 as being deleted when it's not (Rich Diff shows correctly).

Lines 33 -> 37 are the ones that were duplicated with what I removed at lines 66->70

**Pull request merged**
