### PR TITLE
[WIP] How to run the distributor and workers on a single machine

### PR DESCRIPTION
**Pull request by ramonsmits**
**This is a work-in-progress**

Separate document explaining which options are available to run both the distributor and the worker on the same machine for testing and demonstration purposes.

It reuses a bit of the distributor sample and the distributor main page to be complete.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@ramonsmits are you still working on this?

**Comment by SimonCropp** [comment]
@SzymonPobiega @ramonsmits given the distributor is being deprecated in v6 can this be killed?

**Comment by SimonCropp** [comment]
@SzymonPobiega @ramonsmits ping

**Comment by SzymonPobiega** [comment]
I mean, there is still value for users who are on 5 and older and continue to be there. So if it is not a significant effort to finish this guide, maybe we should?

Probably a more important thing now would be a guide I mentioned in https://github.com/Particular/NServiceBus/issues/3437 that shows users how to switch from distributor+worker in single endpoint to a stand-alone distributor.

**Comment by SimonCropp** [comment]
@ramonsmits if u no longer think this is required i will delete the PR.

**Pull request closed without merging**
