### PR TITLE
Remove the showcase sample for V8

### PR DESCRIPTION
**Pull request by WilliamBZA**

### CODE REVIEW

**Review by ramonsmits — APPROVED** [review]

**Comment by udidahan** [comment]
Some extra explanation as to why this was done may be helpful.

**Comment by ramonsmits** [comment]
@udidahan The sample was already incompabitle with -alpha/beta/rc but wasn't spotted due to a Nuget version range bug/behavior. It would break at runtime. Its tracked that this sample is dropped and might be restored with a compatible version in the future.

**Comment by udidahan** [comment]
OK - it would have been better to have that in the description of this PR though.

**Comment by ramonsmits** [comment]
> OK - it would have been better to have that in the description of this PR though.

@udidahan Makes sense, done!

**Pull request merged**
