### PR TITLE
Update Custom Checks sample and snippets to beta 6 (Core beta 7)

### PR DESCRIPTION
**Pull request by mikeminutillo**
Connects to https://github.com/Particular/V6Launch/issues/65

To be merged when the Custom Checks plugin is pushed to NuGet.

### CODE REVIEW

**Comment by weralabaj** [comment]
@mikeminutillo generally if the package is on myget, we merge related docs. can we do that with this one too?

**Comment by mikeminutillo** [comment]
@weralabaj if someone downloads the sample and attempts a NuGet restore without having the MyGet feed configured it will fail.

I may need to revisit this one tomorrow anyway as the plugin was updated for the Beta6 release but not yet for Beta7 (it will probably work just fine but I need to verify)

**Comment by weralabaj** [comment]
OK

>  if someone downloads the sample and attempts a NuGet restore without having the MyGet feed configured it will fail

That would happen for other packages anyway, so I wouldn't worry too much. Might be also good to raise it as a concern for Launch. I think the reason is that nobody expected those updates will take so much time overall :/

**Comment by mikeminutillo** [comment]
No worries. Like I said, I need to quickly revisit this one tomorrow and I suspect that by the time I'm done the core change will be pushed and I can push the updated plugins to NuGet as well.

**Comment by SimonCropp** [comment]
Confused. All samples have the myget feed configured

**Comment by mikeminutillo** [comment]
Ah yes. @SimonCropp is correct :) I withdraw my concern. The fact that this still needs a potential update remains though.

**Comment by mikeminutillo** [comment]
Good to go

**Comment by weralabaj** [comment]
rebased, waiting for TC checks to pass before merging

**Pull request merged**
