### PR TITLE
Merging IEndpointInsance and IBusSession together

### PR DESCRIPTION
**Pull request by hmemcpy**
Relates to https://github.com/Particular/NServiceBus/pull/3356

### CODE REVIEW

**Comment by SimonCropp** [comment]
can u rebase?

**Comment by hmemcpy** [comment]
@SimonCropp done

**Comment by hmemcpy** [comment]
It's gone a bit messy, but @mat-mcloughlin should squish those commits together.

**Comment by hmemcpy** [comment]
Ready for merge: @Particular/documentation @Particular/tf-handlercontext, please review.

**Comment by SimonCropp** [comment]
merged here https://github.com/Particular/docs.particular.net/commit/63c5bedb76dac3adcb8a411a51883824884b7a55

**Pull request closed without merging**
