### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by DavidBoike**

### CODE REVIEW

**Comment by DavidBoike** [comment]
@Particular/logging-maintainers I ran the NuGet update script, and the build for `\samples\logging\anotar\Anotar_3.3\AnotarLogging.sln` is failing. As part of the update Fody was updated from 2.0.9 to 2.0.10.

Can you investigate?

**Comment by weralabaj** [comment]
Seems like Anotar.NServiceBus.Logging is looking for Fody 2.0.9 explicitly, @SimonCropp shouldn't that work for the 2.0.10 (stable)?

**Comment by SimonCropp** [comment]
nuget.exe does not update targets correctly https://github.com/Particular/docs.particular.net/pull/2770/commits/5df07ea7a241a938cb9fa46f665394d2314ad15e

it was fixed last week on nuget master. so hopefully will come down the next time we update nuget.exe

**Comment by weralabaj** [comment]
cool

**Pull request merged**
