### PR TITLE
WIP: upgrade show-case dependencies 

### PR DESCRIPTION
**Pull request by SeanFeldman**
This PR is to address issue #731 

@weralabaj & @petersgiles could you please help with JS/CSS dependencies upgrade?

### CODE REVIEW

**Comment by petersgiles** [comment]
@SeanFeldman I misunderstood what you wanted and I just went and did this in another branch and your changes pretty much matched mine. So I discarded mine in preference for yours.

**Comment by SimonCropp** [comment]
also should the dependencies be pulled in through nuget or through a cdn eg

   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css" />

**Comment by petersgiles** [comment]
Which would you prefer?

**Comment by SimonCropp** [comment]
i prefer the cdn. although i am not sure it is possible with signalr and it dependencies??

**Comment by SeanFeldman** [comment]
I don't think we should pull from CDN. This is a showcase, sample, not
production code.

**Comment by petersgiles** [comment]
OK, We can look into that. In short, you pretty much want the latest of everything, served from the cloud where possible.

**Comment by SimonCropp** [comment]
I just want the least moving pieces and the simplest to update moving forward.

nuget is in the process of deprecating content nuget packages. which means will JS nugets are dead and just dont know it yet

**Comment by SimonCropp** [comment]
but i will defer to the guys doing the work ;)

**Comment by petersgiles** [comment]
Ok CDN it is. :)

**Comment by petersgiles** [comment]
@SeanFeldman I've made it use CDN's for the static assets and I've made it work a little nicer in bootstrap 3.

@SimonCropp  If you're happy with this I'm happy with it.

**Pull request merged**
