### PR TITLE
AwsLambda.Sqs private preview

### PR DESCRIPTION
**Pull request by tmasternak**

### CODE REVIEW

**Comment by udidahan** [comment]
Quick question - if the user doesn't specify a custom serializer, is there a default one?

**Comment by tmasternak** [comment]
@udidahan yes. The configuration defaults to `NewtonsoftJson`.

**Comment by udidahan** [comment]
It might be worth mentioning that in the Serializer section of the doc.

**Comment by tmasternak** [comment]
Default serializer note covered in https://github.com/Particular/docs.particular.net/pull/4996

**Comment by tmasternak** [comment]
☝️ scratch that. There is no default serializer - I got confused.

**Comment by udidahan** [comment]
Then *that* is probably something worth including in the text so that users know they **have to** specify a serializer.

**Comment by adamralph** [comment]
I included that in my [editorial review](https://github.com/Particular/docs.particular.net/pull/4997).

**Pull request merged**
