### PR TITLE
Removing NServiceBus.Hosting.Azure to avoid collision

### LINKED ISSUE #905: Snippet solution doesn't compile
In the process of writing documentation for `TransportMessage` obsoletion. The solution on latest master for the snippets doesn't compile. @andreasohlund verified as well. See below error message.

```
Severity    Code    Description    Project    File    Line
Error    CS0433    The type 'IProfile' exists in both 'NServiceBus.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Hosting.Azure, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'    Snippets_5    C:\dev\docs.particular.net\Snippets\Snippets_5\Logging\OverrideViaProfile.cs    22

andreas [15:44]
and

andreas [15:44]
Severity    Code    Description    Project    File    Line
Error    CS0433    The type 'IConfigureLoggingForProfile<T>' exists in both 'NServiceBus.Host, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' and 'NServiceBus.Hosting.Azure, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'    Snippets_5    C:\dev\docs.particular.net\Snippets\Snippets_5\Logging\OverrideViaProfile.cs    11
```

I'm parking this here for now to finish my doco task and come back to this as soon as I have time.

### PR DESCRIPTION
**Pull request by SeanFeldman**
fixes #905

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@andreasohlund @SimonCropp this should fix the issue.

**Comment by SimonCropp** [comment]
Rather than faking something, that wont properly break when we update to a major with breaking changes, why not put it in its own project

**Comment by SeanFeldman** [comment]
@SimonCropp works for me.
What should be the project name to allow snippets scanning?

**Comment by SimonCropp** [comment]
Project name doesnt matter. It scanns file extention for everything in "snippets"

**Pull request merged**
