### PR TITLE
Update testing page

### PR DESCRIPTION
**Pull request by weralabaj**
Resolves https://github.com/Particular/docs.particular.net/issues/1829

### CODE REVIEW

**Comment by weralabaj** [comment]
@timbussmann looking at https://docs.particular.net/nservicebus/testing/ do you think it makes sense to provide samples of AAA style for anything else than the basic handler and saga tests?

BTW I'm not sure how to get working saga test when saga in the handler calls ReplyToOriginator and RequestTimeout. I might hack it, but that requires knowledge of NSB internals, what's the recommended approach?

**Comment by timbussmann** [comment]
with that approach, it looks like we have a lot of duplicated code from this page: https://docs.particular.net/samples/unit-testing/ ?

**Comment by weralabaj** [comment]
true, but I don't think we can have sample and article combined on a one page :/

**Comment by timbussmann** [comment]
There is no real way of automatically trigger timeouts with the unit testing approach. You would just have to handle the timeout message. You can verify whether a timeout has been requested by something like:

```
var timeout= context.SentMessages.Containing<TimeoutMessage>().Single();
Assert.That(timeout.Options.GetDeliveryDelay(), Is.EqualTo(TimeSpan.FromMinutes(5)));
```

or similar. I think we could provide an extension method which checks the `NServiceBus.Headers.IsSagaTimeoutMessage` header. e.g. something like `Where(m => m.IsSagaTimeout())`. Thoughts?

For ReplyToOriginator you would write:

```
var reply = context.SentMessages.Containing<SubmitOrder>().Single();
Assert.That(reply.Options.GetDestination(), Is.EqualTo(saga.Data.Originator));
```

**Comment by weralabaj** [comment]
@timbussmann I think it might be useful to extend the sample to cover at least the same scenarios as the current article describes for all versions, I'll raise a separate issue though, ok?

**Comment by weralabaj** [comment]
Notes 
[ ] ExpectSagaData is not covered

**Comment by weralabaj** [comment]
@timbussmann  https://github.com/Particular/docs.particular.net/issues/1938

**Comment by danielmarbach** [comment]
Awesome sauce @weralabaj

**Pull request merged**
