### PR TITLE
Added ServicePulse commandline help

### PR DESCRIPTION
**Pull request by ramonsmits**

### CODE REVIEW

**Comment by SimonCropp** [comment]
my concern is keeping it up-to-date as the versions evolve. it is not like the nuget based apis where we can update/version and evolve

**Comment by gbiellem** [comment]
> my concern is keeping it up-to-date as the versions evolve.

:+1: That's where i was coming from as well.  We've had the same issue with SC and NSB Powershell doco.

**Comment by johnsimons** [comment]
cmd line help is available via the popular -? or --help, no need to create a static version of it in my opinion

**Comment by SimonCropp** [comment]
ok based on the comments i am closing this

**Comment by ramonsmits** [comment]
@gbiellem Yes, mentioning that they can use `-?` is fine, but that isn't indexed by google. Yes, it can get out of sync but is that a reason to not put it in the doco? Isn't that an issue for all doco?

**Comment by ramonsmits** [comment]
@gbiellem @SimonCropp Reason for adding this is that a customer wanted to run multiple versions of ServiceControl on a single machine.

And yes, if you run it non elevated you get errors. That also is not really strange as that is expected.

**Comment by ramonsmits** [comment]
@gbiellem What you are addressing is that basically the commandline argument doco itself is broken. If that is the case than that is different from this PR.

**Comment by ramonsmits** [comment]
@gbiellem @SimonCropp Another reason for this doco is that:

1. Arguments as case sensitive
2. Unknown arguments are not resulting in commandline validation errors

I don't really have an issue with 1 is we would have validation.

Due to case sensitivity the customer was not able to manually install the instance as a different windows service.

**Comment by gbiellem** [comment]
@ramonsmits case sensitivity sounds like a bug to me. Agree the command
line doco is broken and so are some of options in my opinion.

**Comment by ramonsmits** [comment]
So @gbiellem should I create two issues in SP:

1. Validate commandline arguments.
2. Fix conflicting argument with constants.

**Comment by ramonsmits** [comment]
Btw, I still see value in just having the output in the doco.

Its also because we don't have a KB. If we had that I could have a KB article.

**Comment by gbiellem** [comment]
@ramonsmits i'd prefer to write an article on installing a second instance
which sounds like what the customer wanted. Much like we have for
servicecontrol

**Comment by gbiellem** [comment]
And I m offering to write it :)

**Comment by ramonsmits** [comment]
@gbiellem You have my vote :-) still, what to do about argument validation?

**Comment by gbiellem** [comment]
Raise a bug - i' ll fix it

**Comment by ramonsmits** [comment]
See https://github.com/Particular/ServicePulse/issues/228

**Comment by gbiellem** [comment]
Thanks @ramonsmits

**Pull request closed without merging**
