### PR TITLE
fix string comparison in Installers sample code

### PR DESCRIPTION
**Pull request by jjanuszkiewicz**
Fix the comparison, as it always evaluated to false.
Also use OrdinalIgnoreCase comparison instead of culture-specific ToLower().

### CODE REVIEW

**Comment by jjanuszkiewicz** [comment]
I can see that the same code exists in the samples for other NSB versions, it would be great if someone fixed that as well.

**Comment by jjanuszkiewicz** [comment]
Fixed in examples for other NSB versions as well.

**Comment by dvdstelt** [comment]
Not sure how we missed that for quite a while! :)

There are conflicting files atm though. We _just removed_ all v3 and v4 snippets. Could you remove those commits, so we can possibly merge this?

**Comment by jjanuszkiewicz** [comment]
No problem, remove those 2 files.

**Comment by dvdstelt** [comment]
Thanks, @jjanuszkiewicz.
I could've done it myself, but I was 'out of the office' and disconnected for a few days.

**Pull request merged**
