### PR TITLE
Updating host profiles doco to include snippets for different versions

### PR DESCRIPTION
**Pull request by johnsimons**
Also removed `Behavior requiring initialization to be complete` section, can't figure out the value in it

### CODE REVIEW

**Comment by SimonCropp** [comment]
thanks

**Comment by johnsimons** [comment]
I don't really understand the value in http://docs.particular.net/nservicebus/hosting/nservicebus-host/profiles#dependent-profile-behaviors either, I would also remove that, not sure what exactly the point it ?

**Comment by SimonCropp** [comment]
@johnsimons that doco pre-dates me. i dont mind removing it, but is there anyone who is more of an expert on the host who can weigh in?

**Comment by johnsimons** [comment]
Only @udidahan and @andreasohlund

**Comment by udidahan** [comment]
@johnsimons do you not understand the value in the docs, or of the feature itself?

**Comment by johnsimons** [comment]
The feature @udidahan

**Comment by udidahan** [comment]
@johnsimons and is the value of Profiles clear?

**Comment by SimonCropp** [comment]
@udidahan to me no. short term appearance of value for long term complexity and overly rigid/opinionated api

**Comment by udidahan** [comment]
@SimonCropp then an issue should be opened in PlatDev to discuss that.

**Comment by johnsimons** [comment]
@udidahan the one I am strugling with is http://docs.particular.net/nservicebus/hosting/nservicebus-host/profiles#dependent_profile-v3_x-4_x

**Comment by udidahan** [comment]
@johnsimons the scenario is that a user may want to create their own types "decorators" for the IConfigureThisEndpoint class like AsA_Publisher - for example, ISendEmails. Then, they would want to have a profile handler which checks to see whether this endpoint sends emails, and if so, customize the way in which that's done.

**Pull request merged**
