### PR TITLE
Make InMemoryPersistence summary clear

### PR DESCRIPTION
**Pull request by SeanFeldman**
Clearly indicate it's NOT for production

@Particular/docs-maintainers

### CODE REVIEW

**Comment by SimonCropp** [comment]
summary only appears on search results and index pages. not in the actual page content

**Comment by SeanFeldman** [comment]
Exactly. The page itself has this info, but the summary doesn't. When this
is the top search result to show up, it looks like something to use...

**Comment by SimonCropp** [comment]
ahh ok

**Comment by SeanFeldman** [comment]
Merge? 😃

**Pull request merged**
