### PR TITLE
WIP add v6 shared host

### LINKED ISSUE #804: Add v6 azure samples
* [x] http://docs.particular.net/samples/azure/blob-storage-databus/
 * [x] http://docs.particular.net/samples/azure/azure-service-bus/
 * [x] http://docs.particular.net/samples/azure/storage-persistence/
 * [x] http://docs.particular.net/samples/azure/storage-queues/
 * [x] http://docs.particular.net/samples/azure/polymorphic-events-asb/
 * [ ] http://docs.particular.net/samples/azure/shared-host/

### PR DESCRIPTION
**Pull request by SimonCropp**
fixes #804

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers this compiles but i am not sure how to smoke test it. can someone give it a once over

**Comment by SeanFeldman** [comment]
Looking into it. Smoke testing is failing (emulator issue). I'll try to figure out what is it and merge if resolved.

**Comment by SimonCropp** [comment]
thanks @SeanFeldman ping me if i can help more

**Comment by SeanFeldman** [comment]
@Particular/azure-maintainers sample fails smoke test. Host is looking for something in `Settings` that doesn't exist.

```
[fabric] Role Instance: deployment27(257).HostCloudService.HostWorker.0
[fabric] Role state Busy
[runtime] Role entrypoint . CALLING   OnStart(): WorkerRole
[runtime] System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
[runtime] Unhandled Exception:
System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception occured: System.Collections.Generic.KeyNotFoundException: The given key (TypesToScan) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 95
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 21
   at NServiceBus.SettingsExtentions.GetConfigSection[T](ReadOnlySettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\SettingsExtentions.cs:line 20
   at NServiceBus.Hosting.Azure.DynamicHostController.Start() in C:\BuildAgent\work\79b79bd92dd94994\src\NServiceBus.Hosting.Azure\DynamicHost\DynamicHostController.cs:line 24
   at WorkerRole.OnStart() in C:\GitHub\nsb\docs.particular.net\samples\azure\shared-host\Version_6\HostWorker\WorkerRole.cs:line 12
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Pull request merged**
