### PR TITLE
WIP: SQLtransport Nhibernate Sample

### PR DESCRIPTION
**Pull request by petersgiles**
Not ready to merge

Connects to https://github.com/Particular/NServiceBus.NHibernate/issues/138

### CODE REVIEW

**Comment by petersgiles** [comment]
Still working on it I currently have this exception

```C#
System.Exception was unhandled
  HResult=-2146233088
  Message=Could not enumerate all types for 'C:\Code\docs.particular.net\samples\sqltransport-nhpersistence\Version_3.0\Sender\bin\Debug\NServiceBus.NHibernate.dll'.
Exceptions:
System.TypeLoadException: Could not load type 'NServiceBus.Timeout.Core.IPersistTimeoutsV2' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
System.TypeLoadException: Method 'Install' in type 'NServiceBus.TimeoutPersisters.NHibernate.Installer.Installer' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'Subscribe' in type 'NServiceBus.Unicast.Subscriptions.NHibernate.SubscriptionPersister' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'Subscribe' in type 'NServiceBus.Unicast.Subscriptions.NHibernate.SubscriptionPersister' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'Install' in type 'NServiceBus.Unicast.Subscriptions.NHibernate.Installer.Installer' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'Get' in type 'NServiceBus.Outbox.OutboxPersister' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'DeduplicateMessage' in type 'NServiceBus.Deduplication.NHibernate.GatewayDeduplication' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Method 'Install' in type 'NServiceBus.Deduplication.NHibernate.Installer.Installer' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Could not load type 'NServiceBus.Saga.ISagaPersister' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
System.TypeLoadException: Could not load type 'NServiceBus.Saga.IContainSagaData' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
System.TypeLoadException: Could not load type 'NServiceBus.Saga.IContainSagaData' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
System.TypeLoadException: Method 'OnStart' in type 'OutboxCleaner' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Could not load type 'NServiceBus.Pipeline.Contexts.IncomingContext' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
System.TypeLoadException: Method 'Install' in type 'NServiceBus.Persistence.NHibernate.Installer' from assembly 'NServiceBus.NHibernate, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
System.TypeLoadException: Could not load type 'NServiceBus.Pipeline.Contexts.IncomingContext' from assembly 'NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.


  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(String assemblyPath, AssemblyScannerResults results) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 226
       at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 106
       at NServiceBus.BusConfiguration.GetAllowedTypes(String path) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\BusConfiguration.cs:line 265
       at NServiceBus.BusConfiguration.Build() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\BusConfiguration.cs:line 203
       at NServiceBus.Endpoint.Prepare(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 17
       at NServiceBus.Endpoint.Create(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 27
       at NServiceBus.Endpoint.<Start>d__2.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 0
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Program.<AsyncMain>d__3.MoveNext() in C:\Code\docs.particular.net\samples\sqltransport-nhpersistence\Version_3.0\Sender\Program.cs:line 47
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Program.Main() in C:\Code\docs.particular.net\samples\sqltransport-nhpersistence\Version_3.0\Sender\Program.cs:line 19
  InnerException: 
```

**Comment by petersgiles** [comment]
ping @SzymonPobiega  @danielmarbach 

Blocked by current build fail
http://builds.particular.net/project.html?projectId=NServiceBusNHibernate

Who is the Taskforce for NServiceBus.NHibernate

**Comment by danielmarbach** [comment]
Exclude me, I'm not

**Comment by SzymonPobiega** [comment]
@petersgiles there is one TF for all the persistences. I was working on the NH one. I've seen this bug and it seems like it is related to the presence of old NSB and new NSB.NH. @timbussmann did you seen that before?

**Comment by timbussmann** [comment]
`IPersistTimeoutsV2` has been added to v5 for a bugfix but does no longer exist in v6, that's causing the exception.

**Comment by petersgiles** [comment]
@timbussmann is it an easy fix?

**Comment by timbussmann** [comment]
@petersgiles I don't think there is anything you can do without the nhibernate package updated to core v6.

**Comment by petersgiles** [comment]
@timbussmann what taskforce is doing that?

**Comment by timbussmann** [comment]
@petersgiles that should be the @Particular/tf-async-persistence taskforce

**Comment by colin-higgins** [comment]
https://github.com/Particular/NServiceBus.NHibernate/issues/138

**Comment by petersgiles** [comment]
@Particular/tf-async-persistence This sample is blocked by the current lack of multi-database support in the SQL Transport. Is there another way to do multi-database? or should we park this sample until Core 6.n?

**Comment by mauroservienti** [comment]
Multi-instance support will be shipped with Core V6 as a sample, it's not
supported anymore directly by the transport, if there is anything here that
depends on that, please, drop it and raise an issue to keep track of what
needs to be added in the other sample.

**Comment by petersgiles** [comment]
@mauroservienti would you please reference the issue that covers creating that sample here

**Comment by mauroservienti** [comment]
Pinged @justabitofcode via Slack, he owns that task.

**Comment by justabitofcode** [comment]
The issue opened to spike a multi connection string extension point is 
https://github.com/Particular/NServiceBus.SqlServer/issues/113
And the issue that covers the multi-database support for V3 is
https://github.com/Particular/NServiceBus.SqlServer/issues/139

**Pull request merged**
