### PR TITLE
Moved the generic points of upgrade to the landing page

### LINKED ISSUE #2270: Cleaning up of the upgrade landing page
Some of the generic content are in the 5-to-6 page which needs to be moved up.

https://github.com/Particular/docs.particular.net/pull/2271

### PR DESCRIPTION
**Pull request by HEskandari**
Resolves #2270

### CODE REVIEW

**Comment by weralabaj** [comment]
@HEskandari should you also remove that content from the v5 to v6 page and link to this new one? I can do that later today if you have no time now.

**Comment by HEskandari** [comment]
@weralabaj Would be great if you could. There's been little rewording but should be easy to find the changes.

**Comment by weralabaj** [comment]
sure!

**Comment by weralabaj** [comment]
@Particular/docs-maintainers since I made quite a few changes, can this be verified by one more person?

**Pull request merged**
