### PR TITLE
Metrics section reformatted

### PR DESCRIPTION
**Pull request by Scooletz**
This PR creates a nested structure for `metrics` in `nservicebus/operations` gathering all the metrics related topics under one main menu item. The same operation is applied for physical structure of docs, moving all the metrics related `.md` files under `nservicebus/operations/metrics`

The new structure is:
- `/metrics` - just descriptions and rationale behind considering metrics important
  - `/metrics/performance-counters` Configure reporting to Performance Counters
  - `/metrics/service-control` Configure reporting to Service Control
  - `/metrics/raw` Consume raw data from Metrics (this also includes all the configuration for reporting to third parties)

### CODE REVIEW

**Comment by Scooletz** [comment]
Ping @Particular/metrics-maintainers for some input on this

**Comment by Scooletz** [comment]
Ping @Particular/metrics-maintainers This PR is ready for a review. 
Once it's reviewed by you, I'll ping doco maintainers and we'll have a nice and shiny doco for metrics :)

**Comment by Scooletz** [comment]
@Particular/docs-maintainers Can I ask you for a review? I think we can run two reviews at the same time.

**Comment by weralabaj** [comment]
I have a few questions/comments but not related to this restructure in particular. If you plan on updating metrics doco we can discuss them, e.g.
- In Performance counters we have the phrase "Added in version 3", would be clearer as "Added in NServiceBus version 3", since we soon will have the version 3 of the extracted package too ;)
- I'm not sure why we have non-standard versioning in the dropdown, e.g. on this page http://localhost:58982/nservicebus/operations/metrics/performance-counters, i.e. performance counters 1.x and 1.1 are separate pages, that doesn't seem right.

capture

**Comment by dvdstelt** [comment]
@Scooletz It's looking good, but it's also hard to get an overview with all the partials, links, etc.
I suggest you give a heads up when deploying this, so that we can have several people verify if everything is okay on the doco site itself as well?

**Comment by weralabaj** [comment]
@dvdstelt I built it locally and clicked through menu, seems fine. But I agree would be good to give another quick smoke test after it's deployed ;)

**Comment by dvdstelt** [comment]
@weralabaj Both @Scooletz and I don't have the engine running locally, that's why I mentioned testing it again on live.

I'd love to have it running locally though, but haven't tried to get it to work yet. How hard is it!? 😇

**Pull request merged**
