### PR TITLE
Added info to upgrade guide for using transport connection in the handler

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Blocked by https://github.com/Particular/NServiceBus.SqlServer/pull/252

### CODE REVIEW

**Comment by indualagarsamy** [comment]
@SzymonPobiega - is this still WIP?

**Comment by SzymonPobiega** [comment]
@indualagarsamy yes. It depends on https://github.com/Particular/NServiceBus.SqlServer/pull/252

**Comment by SimonCropp** [comment]
@SzymonPobiega @Particular/sqlserver-transport-maintainers so 252 is merged. does that mean this is unstuck?

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah, this is ready to go.

**Pull request merged**
