### PR TITLE
Add a note about compatibility with outbox

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by DavidBoike** [comment]
Well, not true. You can use Outbox, you'd just have to explicitly set the SendsAtomic transaction level.

**Comment by SeanFeldman** [comment]
> You can use Outbox, you'd just have to explicitly set the SendsAtomic transaction level.

You mean setting it up during endpoint configuration stage?

**Comment by SeanFeldman** [comment]
@DavidBoike, have a look. I've updated the change to reflect that the default transport TX mode can be set explicitly to allow the sample to be used with the outbox feature.

**Comment by SeanFeldman** [comment]
The outbox documentation also has a note on this topic: https://docs.particular.net/nservicebus/outbox/#enabling-the-outbox

**Pull request merged**
