### PR TITLE
[Core 6.2] Remove double-opt-in doc for v6

### PR DESCRIPTION
**Pull request by timbussmann**
relates to https://github.com/Particular/NServiceBus/pull/4440

Is the partial version [5,5] correct?

### CODE REVIEW

**Comment by SimonCropp** [comment]
give https://github.com/Particular/NServiceBus/issues/4183 is not released yet should this be WIP?

**Comment by timbussmann** [comment]
good point 👍

**Comment by weralabaj** [comment]
@timbussmann can that be merged now?

**Comment by timbussmann** [comment]
@weralabaj 6.2 is still not released.

**Pull request merged**
