### PR TITLE
ASB RC4 upgrade

### PR DESCRIPTION
**Pull request by SeanFeldman**

### CODE REVIEW

**Comment by SimonCropp** [comment]
why WIP? looks good

**Comment by SeanFeldman** [comment]
https://s-media-cache-ak0.pinimg.com/564x/42/a0/c8/42a0c868fad26ccebf123244cf6da8b5.jpg
image

smoke testing samples

**Comment by SimonCropp** [comment]
@SeanFeldman fair nuf. i usually smoke test before pushing the PR. hence my  confusion

**Comment by SeanFeldman** [comment]
I have tortoise memory. So a WIP PR is a reminder for me :)

**Comment by SeanFeldman** [comment]
@SimonCropp good to go :) Thank you.

**Pull request merged**
