### PR TITLE
[WIP] NSB 6.3

### PR DESCRIPTION
**Pull request by SimonCropp**
## Smoke Tested

Note we do not need full smoke test coverage here

 * [ ] [azure-service-bus](https://docs.particular.net/samples/azure/azure-service-bus)
 * [ ] [azure-service-bus-long-running](https://docs.particular.net/samples/azure/azure-service-bus-long-running)
 * [ ] [azure-service-fabric-routing](https://docs.particular.net/samples/azure/azure-service-fabric-routing)
 * [ ] [blob-storage-databus](https://docs.particular.net/samples/azure/blob-storage-databus)
 * [ ] [custom-partitioning-asb](https://docs.particular.net/samples/azure/custom-partitioning-asb)
 * [ ] [custom-sanitization-asb](https://docs.particular.net/samples/azure/custom-sanitization-asb)
 * [ ] [native-integration-asb](https://docs.particular.net/samples/azure/native-integration-asb)
 * [ ] [performance-tuning-asb](https://docs.particular.net/samples/azure/performance-tuning-asb)
 * [ ] [polymorphic-events-asb](https://docs.particular.net/samples/azure/polymorphic-events-asb)
 * [ ] [shared-host](https://docs.particular.net/samples/azure/shared-host)
 * [ ] [storage-persistence](https://docs.particular.net/samples/azure/storage-persistence)
 * [ ] [storage-queues](https://docs.particular.net/samples/azure/storage-queues)
 * [x] [callbacks](https://docs.particular.net/samples/callbacks)
 * [x] [consumer-driven-contracts](https://docs.particular.net/samples/consumer-driven-contracts)
 * [x] [containers](https://docs.particular.net/samples/containers/)
 * [ ] [monitoring3rdparty](https://docs.particular.net/samples/custom-checks/monitoring3rdparty)
 * [x] [custom-transport](https://docs.particular.net/samples/custom-transport)
 * [x] [delayed-delivery](https://docs.particular.net/samples/delayed-delivery)
 * [x] [encryption](https://docs.particular.net/samples/encryption/)
 * [x] [endpoint-configuration](https://docs.particular.net/samples/endpoint-configuration)
 * [x] [entity-framework](https://docs.particular.net/samples/entity-framework)
 * [x] [errorhandling](https://docs.particular.net/samples/errorhandling)
 * [x] [faulttolerance](https://docs.particular.net/samples/faulttolerance)
 * [x] [feature](https://docs.particular.net/samples/feature)
 * [x] [file-share-databus](https://docs.particular.net/samples/file-share-databus)
 * [x] [fullduplex](https://docs.particular.net/samples/fullduplex)
 * [x] [gateway](https://docs.particular.net/samples/gateway)
 * [x] [handler-ordering-by-interface](https://docs.particular.net/samples/handler-ordering-by-interface)
 * [x] [header-manipulation](https://docs.particular.net/samples/header-manipulation)
 * [x] [hosting](https://docs.particular.net/samples/hosting/)
 * [ ] [kafka](https://docs.particular.net/samples/kafka)
 * [x] [learning-transport](https://docs.particular.net/samples/learning-transport)
 * [x] [logging](https://docs.particular.net/samples/logging/)
 * [x] [mailer](https://docs.particular.net/samples/mailer)
 * [x] [message-error-handling](https://docs.particular.net/samples/message-error-handling)
 * [x] [messagemutators](https://docs.particular.net/samples/messagemutators)
 * [x] [tracing](https://docs.particular.net/samples/metrics/tracing)
 * [x] [mongodb](https://docs.particular.net/samples/mongodb)
 * [x] [mongodb-databus](https://docs.particular.net/samples/mongodb-databus)
 * [ ] [msmqtosqlrelay](https://docs.particular.net/samples/msmqtosqlrelay)
 * [x] [custom-mappings](https://docs.particular.net/samples/nhibernate/custom-mappings)
 * [x] [simple](https://docs.particular.net/samples/nhibernate/simple)
 * [x] [non-durable-messaging](https://docs.particular.net/samples/non-durable-messaging)
 * [ ] [outbox](https://docs.particular.net/samples/outbox/)
 * [x] [performance-counters](https://docs.particular.net/samples/performance-counters)
 * [x] [pipeline](https://docs.particular.net/samples/pipeline/)
 * [x] [plugin-based-config](https://docs.particular.net/samples/plugin-based-config)
 * [x] [pubsub](https://docs.particular.net/samples/pubsub)
 * [ ] [rabbitmq](https://docs.particular.net/samples/rabbitmq/)
 * [x] [ravendb simple](https://docs.particular.net/samples/ravendb/simple)
 * [ ] [custom](https://docs.particular.net/samples/routing/custom)
 * [x] [data-distribution](https://docs.particular.net/samples/routing/data-distribution)
 * [x] [fair-distribution](https://docs.particular.net/samples/routing/fair-distribution)
 * [x] [file-based-routing](https://docs.particular.net/samples/routing/file-based-routing)
 * [x] [instance-mapping-file](https://docs.particular.net/samples/routing/instance-mapping-file)
 * [x] [routing-slips](https://docs.particular.net/samples/routing-slips)
 * [x] [migration](https://docs.particular.net/samples/saga/migration)
 * [x] [nh-custom-sagafinder](https://docs.particular.net/samples/saga/nh-custom-sagafinder)
 * [x] [ravendb-custom-sagafinder](https://docs.particular.net/samples/saga/ravendb-custom-sagafinder)
 * [x] [simple](https://docs.particular.net/samples/saga/simple)
 * [x] [sql-sagafinder](https://docs.particular.net/samples/saga/sql-sagafinder)
 * [x] [scaleout](https://docs.particular.net/samples/scaleout/distributor)
 * [x] [scheduling](https://docs.particular.net/samples/scheduling)
 * [x] [serializers](https://docs.particular.net/samples/serializers/)
 * [ ] [events-subscription](https://docs.particular.net/samples/servicecontrol/events-subscription)
 * [ ] [cloud-azure](https://docs.particular.net/samples/show-case/cloud-azure)
 * [x] [on-premise](https://docs.particular.net/samples/show-case/on-premise)
 * [ ] [sql-bridge](https://docs.particular.net/samples/sql-bridge)
 * [x] [sql-persistence](https://docs.particular.net/samples/sql-persistence/)
 * [x] [multi-instance](https://docs.particular.net/samples/sqltransport/multi-instance)
 * [ ] [native-integration](https://docs.particular.net/samples/sqltransport/native-integration)
 * [x] [sqltransport simple](https://docs.particular.net/samples/sqltransport/simple)
 * [ ] [store-and-forward](https://docs.particular.net/samples/sqltransport/store-and-forward)
 * [x] [sqltransport-nhpersistence](https://docs.particular.net/samples/sqltransport-nhpersistence)
 * [x] [sqltransport-sqlpersistence](https://docs.particular.net/samples/sqltransport-sqlpersistence)
 * [x] [startup-shutdown-sequence](https://docs.particular.net/samples/startup-shutdown-sequence)
 * [x] [step-by-step](https://docs.particular.net/samples/step-by-step)
 * [x] [throttling](https://docs.particular.net/samples/throttling)
 * [x] [unit-of-work](https://docs.particular.net/samples/unit-of-work)
 * [x] [unit-testing](https://docs.particular.net/samples/unit-testing)
 * [x] [unobtrusive](https://docs.particular.net/samples/unobtrusive)
 * [x] [username-header](https://docs.particular.net/samples/username-header)
 * [x] [versioning](https://docs.particular.net/samples/versioning)
 * [x] [web](https://docs.particular.net/samples/web/)

## Moved to Learning

We do want, as much as possible, to use the learning transport and persistence since it lowers friction for consumers of samples

 * [azure-service-bus](https://docs.particular.net/samples/azure/azure-service-bus)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [azure-service-bus-long-running](https://docs.particular.net/samples/azure/azure-service-bus-long-running)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [azure-service-fabric-routing](https://docs.particular.net/samples/azure/azure-service-fabric-routing)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [blob-storage-databus](https://docs.particular.net/samples/azure/blob-storage-databus)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [custom-partitioning-asb](https://docs.particular.net/samples/azure/custom-partitioning-asb)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [custom-sanitization-asb](https://docs.particular.net/samples/azure/custom-sanitization-asb)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [native-integration-asb](https://docs.particular.net/samples/azure/native-integration-asb)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [performance-tuning-asb](https://docs.particular.net/samples/azure/performance-tuning-asb)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [polymorphic-events-asb](https://docs.particular.net/samples/azure/polymorphic-events-asb)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [shared-host](https://docs.particular.net/samples/azure/shared-host)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [storage-persistence](https://docs.particular.net/samples/azure/storage-persistence)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [storage-queues](https://docs.particular.net/samples/azure/storage-queues)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [callbacks](https://docs.particular.net/samples/callbacks)
   * [x] Persistence
   * [x] Transport
 * [consumer-driven-contracts](https://docs.particular.net/samples/consumer-driven-contracts)
   * [x] Persistence
   * [x] Transport
 * [containers](https://docs.particular.net/samples/containers/)
   * [x] Persistence
   * [x] Transport
 * [monitoring3rdparty](https://docs.particular.net/samples/custom-checks/monitoring3rdparty)
   * [x] Not required
 * [custom-transport](https://docs.particular.net/samples/custom-transport)
   * [x] Not required
 * [delayed-delivery](https://docs.particular.net/samples/delayed-delivery)
   * [x] Persistence
   * [x] Transport
 * [encryption](https://docs.particular.net/samples/encryption/)
   * [x] Persistence
   * [x] Transport
 * [endpoint-configuration](https://docs.particular.net/samples/endpoint-configuration)
   * [x] Persistence
   * [x] Transport
 * [entity-framework](https://docs.particular.net/samples/entity-framework)
   * [x] Not required
 * [errorhandling](https://docs.particular.net/samples/errorhandling)
   * [x] Persistence
   * [x] Transport
 * [faulttolerance](https://docs.particular.net/samples/faulttolerance)
   * [x] Persistence
   * [x] Transport
 * [feature](https://docs.particular.net/samples/feature)
   * [x] Persistence
   * [x] Transport
 * [file-share-databus](https://docs.particular.net/samples/file-share-databus)
   * [x] Persistence
   * [x] Transport
 * [fullduplex](https://docs.particular.net/samples/fullduplex)
   * [x] Persistence
   * [x] Transport
 * [gateway](https://docs.particular.net/samples/gateway)
   * [x] Transport
 * [handler-ordering-by-interface](https://docs.particular.net/samples/handler-ordering-by-interface)
   * [x] Persistence
   * [x] Transport
 * [header-manipulation](https://docs.particular.net/samples/header-manipulation)
   * [x] Persistence
   * [x] Transport
 * [hosting](https://docs.particular.net/samples/hosting/)
   * [x] Persistence
   * [x] Transport
 * [kafka](https://docs.particular.net/samples/kafka)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [learning-transport](https://docs.particular.net/samples/learning-transport)
   * [x] Persistence
   * [x] Transport
 * [logging](https://docs.particular.net/samples/logging/)
   * [x] Persistence
   * [x] Transport
 * [mailer](https://docs.particular.net/samples/mailer)
   * [x] Persistence
   * [x] Transport
 * [message-error-handling](https://docs.particular.net/samples/message-error-handling)
   * [x] Persistence
   * [x] Transport
 * [messagemutators](https://docs.particular.net/samples/messagemutators)
   * [x] Persistence
   * [x] Transport
 * [tracing](https://docs.particular.net/samples/metrics/tracing)
   * [x] Persistence
   * [x] Transport
 * [mongodb](https://docs.particular.net/samples/mongodb)
   * [x] Transport
 * [mongodb-databus](https://docs.particular.net/samples/mongodb-databus)
   * [x] Transport
 * [msmqtosqlrelay](https://docs.particular.net/samples/msmqtosqlrelay)
   * [x] Not required
 * [custom-mappings](https://docs.particular.net/samples/nhibernate/custom-mappings)
   * [x] Transport
 * [nhibernate simple](https://docs.particular.net/samples/nhibernate/simple)
   * [x] Transport
 * [non-durable-messaging](https://docs.particular.net/samples/non-durable-messaging)
   * [x] Not required
 * [multi-tenant](https://docs.particular.net/samples/outbox/multi-tenant)
   * [x] Not required
 * [performance-counters](https://docs.particular.net/samples/performance-counters)
   * [x] Persistence
   * [x] Transport
 * [pipeline](https://docs.particular.net/samples/pipeline/)
   * [x] Persistence
   * [x] Transport
 * [plugin-based-config](https://docs.particular.net/samples/plugin-based-config)
   * [x] Persistence
   * [x] Transport
 * [pubsub](https://docs.particular.net/samples/pubsub)
   * [x] Not required
 * [rabbitmq](https://docs.particular.net/samples/rabbitmq/)
   * [x] Not required
 * [ravendb simple](https://docs.particular.net/samples/ravendb/simple)
   * [x] Not required
 * [routing custom](https://docs.particular.net/samples/routing/custom)
   * [x] Not required
 * [data-distribution](https://docs.particular.net/samples/routing/data-distribution)
   * [x] Not required
 * [fair-distribution](https://docs.particular.net/samples/routing/fair-distribution)
   * [x] Not required
 * [file-based-routing](https://docs.particular.net/samples/routing/file-based-routing)
   * [x] Persistence
   * [x] Transport
 * [instance-mapping-file](https://docs.particular.net/samples/routing/instance-mapping-file)
   * [x] Not required
 * [routing-slips](https://docs.particular.net/samples/routing-slips)
   * [x] Persistence
   * [x] Transport
 * [migration](https://docs.particular.net/samples/saga/migration)
   * [x] Transport
 * [nh-custom-sagafinder](https://docs.particular.net/samples/saga/nh-custom-sagafinder)
   * [x] Not required
 * [ravendb-custom-sagafinder](https://docs.particular.net/samples/saga/ravendb-custom-sagafinder)
   * [x] Not required
 * [saga simple](https://docs.particular.net/samples/saga/simple)
   * [x] Persistence
   * [x] Transport
 * [sql-sagafinder](https://docs.particular.net/samples/saga/sql-sagafinder)
   * [x] Transport
 * [distributor](https://docs.particular.net/samples/scaleout/)
   * [x] Not required
 * [scheduling](https://docs.particular.net/samples/scheduling)
   * [x] Persistence
   * [x] Transport
 * [serializers](https://docs.particular.net/samples/serializers/)
   * [x] Persistence
   * [x] Transport
 * [events-subscription](https://docs.particular.net/samples/servicecontrol/events-subscription)
   * [ ] Not required
   * [ ] Persistence
   * [ ] Transport
 * [show-case](https://docs.particular.net/samples/show-case/)
   * [x] Not required
 * [sql-bridge](https://docs.particular.net/samples/sql-bridge)
   * [x] Not required
 * [sql-persistence](https://docs.particular.net/samples/sql-persistence/)
   * [x] Transport
 * [sqltransport](https://docs.particular.net/samples/sqltransport/simple)
   * [x] Not required
 * [startup-shutdown-sequence](https://docs.particular.net/samples/startup-shutdown-sequence)
   * [x] Persistence
   * [x] Transport
 * [step-by-step](https://docs.particular.net/samples/step-by-step)
   * [x] Persistence
   * [x] Transport
 * [throttling](https://docs.particular.net/samples/throttling)
   * [x] Persistence
   * [x] Transport
 * [unit-of-work](https://docs.particular.net/samples/unit-of-work)
   * [x] Persistence
   * [x] Transport
 * [unit-testing](https://docs.particular.net/samples/unit-testing)
   * [x] Not required
 * [unobtrusive](https://docs.particular.net/samples/unobtrusive)
   * [x] Persistence
   * [x] Transport
 * [username-header](https://docs.particular.net/samples/username-header)
   * [x] Persistence
   * [x] Transport
 * [versioning](https://docs.particular.net/samples/versioning)
   * [x] Persistence
   * [x] Transport
 * [web](https://docs.particular.net/samples/web/)
   * [x] Persistence
   * [x] Transport

## TODO

 * [ ] Remove MessageEndpointMappings from all samples since it now logs an error

### CODE REVIEW

**Comment by SimonCropp** [comment]
@Particular/azure-maintainers 

For each of the azure samples (excluding the showcase) can u tell me which ones are compat with the learning persistence or the learning transport?

**Comment by SeanFeldman** [comment]
@SimonCropp perhaps not compatible, but were it can be used?
If a sample is about ASB transport, I would not want to change that to the learning transport. But if there's a sample of ASP that as a transport is using MSMQ, there I'd say 👍 for using the learning transport. Same applies to the learning persistence. I presume that was the intent of your question.

**Comment by SimonCropp** [comment]
@SeanFeldman correct

But given there are limitations to the learning transport and persistence i actually need an azure person to smoke test and tell me which samples can be changed

**Comment by SeanFeldman** [comment]
Azure samples will be covered by PR #2747

**Pull request merged**
