### PR TITLE
fixup namespace imports

### PR DESCRIPTION
**Pull request by timbussmann**
fix namespace imports related to Particular/NServiceBus#3319

### CODE REVIEW

**Comment by SimonCropp** [comment]
so no samples need to be updated?

**Comment by SimonCropp** [comment]
@timbussmann btw this will update all the nugets https://github.com/Particular/docs.particular.net/blob/master/tools/nugets.linq

**Comment by timbussmann** [comment]
@SimonCropp haven't checked yet. Just created a first WIP PR and will check sample when the packages are available on the MyGet feed.

**Comment by timbussmann** [comment]
@Particular/documentation all samples building again.

**Pull request merged**
