### PR TITLE
WIP: Update connection-settings.md

### PR DESCRIPTION
**Pull request by janpieterz**
Minimum pool size is also required to prevent warning

### CODE REVIEW

**Comment by janpieterz** [comment]
Whoops, never mind:
https://github.com/Particular/NServiceBus.SqlServer/pull/339

**Comment by SzymonPobiega** [comment]
@janpieterz let me reopen it. I think we need to clarify the version numbers in the doco because some versions of SQL 3.x did require also the min value. Thanks for raising this!

**Comment by janpieterz** [comment]
Correct, in the current version I have (latest on nuget) this behavior is present

**Comment by SimonCropp** [comment]
@SzymonPobiega marked this as WIP seeing as u seem to want to make changes?

**Comment by SzymonPobiega** [comment]
@SimonCropp as that change we talked here has not yet been released, I am merging this one and create another [WIP] one to be merged when we release 3.1 of SQL

**Pull request merged**
