### PR TITLE
[WIP] reorg persistence and transports files

### PR DESCRIPTION
**Pull request by weralabaj**
Fixes https://github.com/Particular/docs.particular.net/issues/2864

### CODE REVIEW

**Comment by SimonCropp** [comment]
@weralabaj i took the liberty of fixing some links

**Comment by SimonCropp** [comment]
@weralabaj do u want to merge this as "persistence done" and do transports in another PR?

**Comment by SimonCropp** [comment]
@weralabaj cool. let me know when u r done. there is one more change i would like to do

**Comment by weralabaj** [comment]
@SimonCropp ping

**Comment by weralabaj** [comment]
@SimonCropp I'll do the same change for tranpsorts then :)

**Comment by SimonCropp** [comment]
@weralabaj pending a green build. r u ok with a merge?

**Pull request merged**
