### PR TITLE
Implement additional metrics in Prometheus Sample

### PR DESCRIPTION
**Pull request by bbrandt**
* nservicebus.messaging.criticaltime
* nservicebus.messaging.processingtime
* nservicebus.recoverability.moved_to_error
* nservicebus.recoverability.immediate_retries
* nservicebus.recoverability.delayed_retries
* nservicebus.recoverability.retries

Copied example from App Insights Sample in  #6452

@andreasohlund @danielmarbach @bording 
Is this still the recommended approach for sending metrics to Prometheus?

### CODE REVIEW

**Comment by danielmarbach** [comment]
I'll leave that up to @andreasohlund to comment on, since he has recently been digging into this.

**Comment by andreasohlund** [comment]
Yes this would work until we get this into the core NServieceBus package. You'll need to add shim to the v8 sample as well for the build to be green

**Comment by andreasohlund** [comment]
>Is this still the recommended approach for sending metrics to Prometheus?

Yes, IMO OpenTelemetry is the way to go

**Comment by bbrandt** [comment]
@andreasohlund I've updated the NSB v8 sample as well.

**Pull request merged**
