### PR TITLE
Point users to self-hosting templates in Host upgrade guide

### PR DESCRIPTION
**Pull request by bording**

### CODE REVIEW

**Comment by mauroservienti** [comment]
Sounds like it’s ready to be merged 😊

**Comment by bording** [comment]
@mauroservienti I've got everything green now. I am wondering if we should add a section to the hosting index page that also mentions the docker template, though?

**Comment by mauroservienti** [comment]
Yes, please do. We should bring readers there anyway.
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by bording** [comment]
@mauroservienti If you're happy with the new docker section, I'll go ahead and merge.

**Comment by mauroservienti** [comment]
LGTM 👍🏼

**Pull request merged**
