### PR TITLE
Recovered components index from 5201f45

### PR DESCRIPTION
**Pull request by ramonsmits**
In 5201f45 a lot of content was lost but that was done due reduce maintenance on content for community packages. The listing of the components themselves was also lost which I think is unneeded.

This restores this list of packages which are all from @SimonCropp

### CODE REVIEW

**Comment by ramonsmits** [comment]
@SimonCropp Would you have any problem with re-listing these packages on https://docs.particular.net/components/ ?

**Comment by SimonCropp** [comment]
@ramonsmits has there been someone who has requested this?

**Comment by ramonsmits** [comment]
@SimonCropp Yes, a customer requested information on binary serializers. I wanted to point to the index to share known community options.

**Comment by SimonCropp** [comment]
ok. no objections

A couple of things with this PR

 * u might want to add https://github.com/NServiceBusExtensions/Verify.NServiceBus
 * remove HandlerOrdering. it was broken by a recent release of NSB and i can fix it from my side

**Comment by SimonCropp** [comment]
note that you would need to maintain the version compat list

**Comment by DavidBoike** [comment]
This is a heavy-handed and maintenance-laden way to link to community contributions. @ramonsmits if you want to link to mention community-contributed stuff, try editing markdown at the locations below. (These sections don't *have to* link to the extensions page.) It's a lot simpler and easier to maintain:

* https://docs.particular.net/transports/#community-maintained-transports
* https://docs.particular.net/persistence/#community-maintained-persisters
* https://docs.particular.net/nservicebus/serialization/#supported-serializers (Add a new section to mimic transports/persistence)
* I don't think Loggers are really relevant anymore given we [integrate Microsoft.Extensions.Logging](https://docs.particular.net/nservicebus/logging/extensions-logging) now.

**Comment by SimonCropp** [comment]
glad i went to the effort of reviewing the PR

**Comment by ramonsmits** [comment]
@DavidBoike The PR was still in "draft" and not ready for review.  I don't understand why this suddenly gets so much attention. If this is not a good way long term then lets create an issue for that problem or create an issue to change that but this can't just be closed

> This is a heavy-handed and maintenance-laden way to link to community contributions.

While I agree this "one time thing" is heavy, its how it is for all current external packages. Before this PR there were 22 external packages listed. How come it wasn't a problem before this PR and now closing this PR? I think there is a lot of value in having one index that lists *all* extensions.

>if you want to link to mention community-contributed stuff, try editing markdown at the locations below. (These sections don't _have to_ link to the extensions page.) It's a lot simpler and easier to maintain:
 
Yes, we could list them on those pages.

> * I don't think Loggers are really relevant anymore given we [integrate Microsoft.Extensions.Logging](https://docs.particular.net/nservicebus/logging/extensions-logging) now.

Good point, but that is only for NServiceBus 7+.

----

My main point is that this page already contains external (community) contributions and these extensions were on that page before and its about *restoring* those items. This is not about if the method on how these external contributions are managed is bloated or that it can be done different. I don't think this can just be closed because then we should remove *all* prior 22 external contributions from this page as part of this PR.

We can:

1. Merge these restores entries that were there before
2. Remove all external contributions
3. Restructure all external contributions

I would say, go with 1 *first* and then do 3  but I'm fine with improving/simplify the structure of how these entries if that is 'demanded' as part of this PR.

**Comment by DavidBoike** [comment]
Closing in favor of https://github.com/Particular/docs.particular.net/pull/5060

**Pull request closed without merging**
