### PR TITLE
Changing from MessageToSend to MessageTypeToSend to clarify the argum…

### PR DESCRIPTION
**Pull request by mauroservienti**
…ent meaning

### CODE REVIEW

**Comment by SimonCropp** [comment]
I think expand it in the markdown

**Comment by indualagarsamy** [comment]
@SimonCropp - I still think the snippet is incorrect. IMO, if you're providing a snippet, it ought to work. Users shouldn't have to try and dig into why the snippet is wrong.

**Comment by mauroservienti** [comment]
The snippet is just text that does nothing on it's own. I'll propose a change in the doco page to address the meaning of the message type and the implications when using, or not, a full type name.

**Comment by indualagarsamy** [comment]
>The snippet is just text that does nothing on it's own. 

Then why have compilable snippets in the first place. When a user takes the snippet we provide it should work. Would the snippet work, if the user pulled the code from our doco page and used it or would the code result in exceptions are somethings to think about. 

>I'll propose a change in the doco page to address the meaning of the message type and the implications when using, or not, a full type name.

I agree on the detailed explanations on the snippet themselves should belong in the correct documentation. So, if the documentation doesn't address that we ought to fix it. I believe the related doco page for this is http://docs.particular.net/nservicebus/messaging/message-owner

**Comment by mauroservienti** [comment]
> Then why have compilable snippets in the first place. When a user takes the snippet we provide it should work. Would the snippet work, if the user pulled the code from our doco page and used it or would the code result in exceptions are some things to think about.

As far as I can tell there is nothing in that page that mentions a message type so copying that snippet cannot work in any way, if we want to provide a meaningful `MessageTypeToSend` parameter than we should provide the message class as well, otherwise providing something like `MyNamespace.Message, MyAssembly` is as useless as `MessageTypeToSend`.

Or am I missing something?

**Pull request merged**
