### PR TITLE
[WIP] Reviewed SI sequence diagram page

### LINKED ISSUE #2055: The page 'Sequence Diagram' requires review
The page [Sequence Diagram](https://docs.particular.net/serviceinsight/sequence-diagram/) has never been reviewed.

 * [Page review instructions](https://github.com/Particular/docs.particular.net#reviewing-a-page)
 * [Location in GitHub](https://github.com/Particular/docs.particular.net/blob/master/serviceinsight/sequence-diagram/index.md)

### PR DESCRIPTION
**Pull request by adamralph**
Fixes #2055

@Particular/docs-maintainers @Particular/serviceinsight-maintainers please review.

### CODE REVIEW

**Comment by HEskandari** [comment]
Did you see my comments in #2055? does it make sense to add it before I merge?

**Comment by adamralph** [comment]
@HEskandari can you please add another commit which adds that info?

**Comment by HEskandari** [comment]
Sure, I'll update it first thing tomorrow.

**Comment by HEskandari** [comment]
@adamralph Please review my update. I have reviewed your changes and they look fine. Feel free to self-merge.

**Comment by adamralph** [comment]
Thanks @HEskandari.

I reworded the point. Can you please take a look?

**Comment by HEskandari** [comment]
@adamralph looks great. Merging.

**Pull request merged**
