### PR TITLE
Updated to 3.1.1

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SimonCropp** [comment]
does the creation script need to be changed? https://docs.particular.net/transports/sql/operations-scripting#create-queues-the-create-queue-helper-methods

**Comment by SzymonPobiega** [comment]
@SimonCropp yeah, good catch.

**Comment by SimonCropp** [comment]
r there any other varchar/nvarchar changes required on that page?

**Comment by SzymonPobiega** [comment]
Yeah. Fixing all of them now as part of this branch.

**Comment by SzymonPobiega** [comment]
I think I fixed them all. I didn't include sending native delayed messages because I think this would be an overkill.

**Pull request merged**
