### PR TITLE
Switch to snippets in compose and dockerfile

### PR DESCRIPTION
**Pull request by danielmarbach**
Requires https://github.com/Particular/DocsEngine/pull/453

Also documents the other extensions that are supported

### CODE REVIEW

**Comment by bording** [comment]
I don't really like adding snippet comments into the actual file someone will get when the download the sample, but I guess that's not really a new problem since we already do that in the actual code with regions...

**Comment by danielmarbach** [comment]
Exactly. Plus everything we do is samples and not meant to be blindly copied.

**Comment by bording** [comment]
> Exactly. Plus everything we do is samples and not meant to be blindly copied.

Because, you know, that never happens! 😛

**Comment by danielmarbach** [comment]
Requires also https://github.com/Particular/DocsEngine/pull/454

**Pull request merged**
