### PR TITLE
[WIP] Raw Xml Doco and Snippets

### PR DESCRIPTION
**Pull request by danielmarbach**
#579

I added the sample to the integration subfolder which I newly created. Needed to add the Namespace to the messages. If you remove it then the XmlSerializer fails to reflect the namespace.

Doco is missing.

### CODE REVIEW

**Comment by SimonCropp** [comment]
This is one of the messaging approaches that will be going in the "dont do this" category. Why would we want to add a sample that enables this approach?

**Comment by danielmarbach** [comment]
@mauroservienti @ramonsmits @jdrat2000 Any thoughts on this? before I remove the sample. @SimonCropp pointed out that it shouldn't be a sample but documentation with snippets only.

**Comment by SimonCropp** [comment]
@danielmarbach looks good

**Comment by SimonCropp** [comment]
@danielmarbach thanks

**Pull request merged**
