### PR TITLE
Clarify serializers configuration.

### PR DESCRIPTION
**Pull request by weralabaj**
In progress...

### CODE REVIEW

**Comment by SimonCropp** [comment]
@weralabaj isnt that covered here http://docs.particular.net/nservicebus/serialization/xml

**Comment by weralabaj** [comment]
@SimonCropp I don't see it mentioning that xml is the default or that we need to use the same on sending/receiving endpoints. That relates to desk case 12702 btw.
If you think there's a better place for that information I can move it, but that's where I'd go first to understand serialization better.

**Comment by SimonCropp** [comment]
@weralabaj happy with 

> The default serializer is XmlSerializer. In order to use another one configure the endpoint accordingly, 

but perhaps something similar to this http://docs.particular.net/nservicebus/containers/#supported-containers instead of the json example?

**Comment by weralabaj** [comment]
@SimonCropp Ok. i'll rework it.

**Comment by weralabaj** [comment]
@SimonCropp better now?

**Comment by SimonCropp** [comment]
Looks good to me. Pull the trigger

**Pull request merged**
