### PR TITLE
RabbitMQ transport - advantages and disadvantages

### PR DESCRIPTION
**Pull request by weralabaj**
Resolves https://github.com/Particular/docs.particular.net/issues/1244.

### CODE REVIEW

**Comment by weralabaj** [comment]
@Particular/rabbitmq-transport-maintainers please see what else could I include here

**Comment by bording** [comment]
The list you've got looks good to me. Here are a couple other items I can think of.

Possible other advantages:

- Automatically supports multiple instances of an endpoint in a round-robin fashion without any additional configuration
- I need to double check the perf numbers, but I think it's one of the fastest transports now. Not sure we want to get into perf stuff here, though
 

Possible disadvantages:
- You have to deal with duplicate messages (so you have to use the Outbox, or make everything idempotent). This can be tricky around dealing with saga timeouts due to how the timeout manager works.

**Comment by weralabaj** [comment]
Thanks @bording

**Comment by WojcikMike** [comment]
@bording could you please elaborate on this:
> Automatically supports multiple instances of an endpoint in a round-robin fashion without any additional configuration

As I don't know what exactly do you mean.

When it comes to the list of + and - I know that @andreasohlund on his talk was ranting a lot about how badly Rabbit handle network partitioning which might cause messages loses:
https://www.rabbitmq.com/partitions.html

I don't know how to describe it in clear way.

**Comment by MarcinHoppe** [comment]
@WojcikMike Can we use something mentioning scale-out using the Competing Consumers pattern? I think this is a phrase that we've used in the past.

**Comment by WojcikMike** [comment]
@MarcinHoppe I think this is a question to Brandon, as I am almost sure that as a broker we support competing consumers OOB.

**Comment by weralabaj** [comment]
Regarding performance, this is what we say for SQL Server "Maximum throughput for any given endpoint is on par with MSMQ.".

**Comment by SimonCropp** [comment]
> "Maximum throughput for any given endpoint is on par with MSMQ.".

i dont know how anyone can make that claim. broker versus distributed queue, they have very difference performance under various types of load

**Comment by weralabaj** [comment]
well... we do :P possibly sql then needs editing.

**Comment by MarcinHoppe** [comment]
@SimonCropp @weralabaj I agree we should probably remove this claim. PR is on the way...

**Comment by weralabaj** [comment]
ping @Particular/docs-maintainers

**Comment by bording** [comment]
@WojcikMike The point I was trying to make is that since RabbitMQ pushes messages to the endpoints instead of the endpoints polling, the broker is responsible for distributing messages to the available consumers, and it does so in a round-robin fashion. To get this behavior with RabbitMQ, you just start another instance of your same endpoint.

To get similar behavior with MSMQ, for example, you have to use the distributor (V5), or sender-side distribution (V6), and that requires additional infrastructure or configuration changes to the endpoint.

**Comment by SimonCropp** [comment]
@bording re this https://github.com/Particular/docs.particular.net/pull/1626#issuecomment-228191647  so is this extra content u still think this PR requires?

**Comment by bording** [comment]
@SimonCropp Seems like this line:
>  Supports [Competing consumers](http://www.enterpriseintegrationpatterns.com/patterns/messaging/CompetingConsumers.html) pattern. Messages are received by instances in a round-robin fashion.

Covers its well enough, but maybe something that speaks to the part about not needing any extra config/modification to the endpoint to gain the benefit?

**Comment by weralabaj** [comment]
@SimonCropp I added what @bording suggested

**Pull request merged**
