### PR TITLE
Resolving RyuJIT issues

### PR DESCRIPTION
**Pull request by ramonsmits**
@SimonCropp As Aaron confirmed, disabling RyuJIT helped resolve the issue. Having **KB3083185** installed does not resolve the issue.

### CODE REVIEW

**Comment by SimonCropp** [comment]
So this is realy good content. however i am not sure this should be doco? so "doco should long lived" depending on the outcome of this https://connect.microsoft.com/VisualStudio/feedback/details/1749339/typeinitializationexception-when-ryujit-is-enabled and this https://groups.google.com/forum/#!topic/particularsoftware/VfBfwRiznyE it may result in a windows update release to .net in which case this page might become irrelevant. or we might do a patch in which case this page would become irrelevant. 

I think we should hold off on documenting this till we have more info. However in the short term i think the content of this should be reworked to an announcement that is sent to all clients via email and posted on the group.

@ramonsmits thoughts?

**Comment by andreasohlund** [comment]
+1 to convert to a customer communication for now.

**Comment by andreasohlund** [comment]
@ramonsmits ping, are you onboard the customer communication idea?


Closing this one for now (reopen if needed)

**Comment by ramonsmits** [comment]
Announcement: https://github.com/Particular/Announcements/issues/36

**Comment by ramonsmits** [comment]
Although this is indeed not real documention, it would fit a knowledge base like system. MSDN also has list of knowledge base articles. Maybe something to consider adopting?

**Pull request closed without merging**
