### PR TITLE
WIP: Implement a custom serializer

### PR DESCRIPTION
**Pull request by johnsimons**
Since the interface is so simple and this is an advance feature, not sure it is worth saying more about it ?

### CODE REVIEW

**Comment by johnsimons** [comment]
Feedback from @SimonCropp:

also in the scope of someone building a serializer how can they possibly ensure "does not clash with any existing registered serializer". they have no idea what other serializers could possible be registered
u have not mentioned the versions
u have not addressed transitioning between versions

**Comment by johnsimons** [comment]
@SimonCropp do you have any suggestions how to better address the points you raised ?

**Comment by SimonCropp** [comment]
@johnsimons no i dont know how to address those. you are the expert on that API. so if u dont have the answers then the API is broken

**Comment by johnsimons** [comment]
Versioning is a tough one, but swapping serializers (xml to json) works reasonably well.
I think we can just say that versioning is not supported ?

**Comment by weralabaj** [comment]
Some ideas on how to move it forward:

> Community run serializers

Apart from this I think it's worth either linking or at least adding as a related header the samples we have, e.g. http://docs.particular.net/samples/serializers/.

> ## How to implement your own serializer
 
 > To implement a serializer all it needs to be done is implement `IMessageSerializer`.
 > The only tricky bit is to ensure that the string returned by `ContentType` does not clash with any existing registered serializer, the `ContentType` string is used internally as a dictionary key lookup.

How about:

- Move it to http://docs.particular.net/nservicebus/serialization/#specifying-additional-deserializers
- Phrase as: "Note: When using multiple deserializers make sure that there's only one type registered per `ContentType`."

Not sure if that also matters in other scenarios? Like when there's clash with default serializer?

**Comment by weralabaj** [comment]
@johnsimons do you plan on updating it or should I take over?

**Comment by johnsimons** [comment]
@weralabaj modified according to your review.

**Comment by johnsimons** [comment]
all your now

**Comment by weralabaj** [comment]
rebased

**Pull request merged**
