### PR TITLE
[WIP]Remove versioning section

### PR DESCRIPTION
**Pull request by andreasohlund**
@Particular/docs-maintainers is this the way to go or do we add partials? (we'll backport the removal to 5.2.X as well)

### WIP

* Upgrade guide

### CODE REVIEW

**Comment by weralabaj** [comment]
yes, seems good

**Comment by weralabaj** [comment]
Instead of removing that section should we say the right way is using interfaces and oint to https://docs.particular.net/samples/versioning/?

**Comment by weralabaj** [comment]
> do we add partials

that still will be a bug in the old versions right? so I would remove it completely

**Comment by andreasohlund** [comment]
>Instead of removing that section should we say the right way is using interfaces and oint to

Not sure our guidance around contract versioning is correct. Will talk to @SimonCropp tomorrow, wan't to join @weralabaj ?

**Comment by weralabaj** [comment]
yes please ping me

**Comment by weralabaj** [comment]
As agreed in the meeting with @andreasohlund and @SimonCropp, merging as it is. New guidance will be handled in the https://github.com/Particular/docs.particular.net/pull/1971

**Pull request merged**
