### PR TITLE
Documentation of feature concept

### PR DESCRIPTION
**Pull request by SzymonPobiega**
**DO NOT MERGE**

 * What is feature
 * Dependencies
 * Enabling, disabling and activation
 * Setting up the container

TODO:
 * Setting up satellite pipelines
 * Possibly merge the queue bindings doco into a section here

### CODE REVIEW

**Comment by timbussmann** [comment]
maybe have a look over [here](https://github.com/Particular/docs.particular.net/pull/813)?

**Comment by SzymonPobiega** [comment]
@timbussmann let's finish and merge yours and then I'll create another PR based on your document.

**Comment by timbussmann** [comment]
@SzymonPobiega my PR is back on master. You wanna close this one?

**Comment by SzymonPobiega** [comment]
Replaced by #843

**Pull request closed without merging**
