### PR TITLE
Add component to ServiceControl and Multi-Instance Mode page

### PR DESCRIPTION
**Pull request by MarcinHoppe**

### CODE REVIEW

**Comment by weralabaj** [comment]
@MarcinHoppe seems that for this page to work, the snippets should be moved from service control solution to sqlserver or you'll need to use a different component in the header (but we only split content based on major versions)

**Comment by MarcinHoppe** [comment]
@weralabaj This is the way it was set up initially. The downside is that ServiceControl snippets get SQL related heading (i.e. would be labeled as `3.x - N NServiceBus.SqlServer`) which is misleading.

**Comment by weralabaj** [comment]
Then it'd be better to move the snippets to the SQL Server solution. I think that makes more sense.

**Comment by MarcinHoppe** [comment]
Of all available solutions, I think what we already have looks and works the best. Closing.

**Pull request closed without merging**
