### PR TITLE
Updates for FaultContext

### PR DESCRIPTION
**Pull request by boblangley**
Connects to https://github.com/Particular/NServiceBus.Gateway/issues/41

https://github.com/Particular/NServiceBus/pull/3694 needs to be merged and Nuget packages updated before this can be merged

### CODE REVIEW

**Comment by weralabaj** [comment]
@boblangley https://github.com/Particular/NServiceBus/pull/3694 was merged, can we remove WIP from this now?

**Comment by SimonCropp** [comment]
@weralabaj i think this  needs to wait until beta2 since until then they is not really a way to update to the new core version

**Comment by boblangley** [comment]
Closing for now until beta 2 nuget is available.

**Comment by boblangley** [comment]
Beta 2 nuget is available and this PR has been updated. Please review and merge.

**Comment by boblangley** [comment]
Addressing conflicts and resubmitting for review/merge shortly

**Comment by boblangley** [comment]
Truly ready for review / merge

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Particular/docs.particular.net/commit/54332b10b52660177e4cecc504e632451b20b55d

**Pull request closed without merging**
