### PR TITLE
[WIP] Rename extentions to extensions

### PR DESCRIPTION
**Pull request by timbussmann**
related to https://github.com/Particular/NServiceBus/pull/3781

Just a marker PR, not ready yet.

### CODE REVIEW

**Comment by danielmarbach** [comment]
Core PR is merged

**Comment by indualagarsamy** [comment]
@timbussmann - ping. Are there any other blockers?

**Comment by timbussmann** [comment]
@indualagarsamy waiting for a new core beta package to update the downstreams.

**Comment by indualagarsamy** [comment]
@timbussmann - any updates?

**Comment by timbussmann** [comment]
closing this as all the relevant places have already been updated through other PRs

**Pull request closed without merging**
