### PR TITLE
ASQ upgrade 6to7

### PR DESCRIPTION
**Pull request by Scooletz**
Connects to https://github.com/Particular/PlatformDevelopment/issues/723

Solves #1275

### CODE REVIEW

**Comment by Scooletz** [comment]
#1275

**Comment by SimonCropp** [comment]
@Scooletz this looks good. want me to handle the conflict and merge?

**Comment by Scooletz** [comment]
@SimonCropp That would be great. I double checked the rest of the scope. It can go in this shape.

**Comment by SimonCropp** [comment]
merged manually

**Pull request closed without merging**
