### PR TITLE
Documented the new SendOptions and ReplyOptions APIs.

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@SzymonPobiega any reason why we would not add equivalents snippets for earlier versions where supported?

**Comment by SzymonPobiega** [comment]
oversight. Let me correct that.

**Comment by SimonCropp** [comment]
@SzymonPobiega thanks. other than that this is good to merge.

**Comment by SzymonPobiega** [comment]
@SimonCropp I've added missing snippets but could not find a way to override the `reply to` for V4 and previous.

**Pull request merged**
