### PR TITLE
Added ravendb license page

### LINKED ISSUE #1981: Need a license page for RavenDb persistence
Some questions/cases are raised about this, which versions they are allowed to use, and to what extent. Seems we could have a license page under 'RavenDB Persistence' for people to refer to.

### PR DESCRIPTION
**Pull request by HEskandari**
Closes #1981

### CODE REVIEW

**Comment by HEskandari** [comment]
@docs-maintainers Please review at your leisure.

**Comment by SimonCropp** [comment]
does it need to be in the menu?

**Comment by HEskandari** [comment]
@SimonCropp yeah, 👍 on adding to the menu...just think under persistence -> ravendb might not be best.

**Comment by SimonCropp** [comment]
> just think under persistence -> ravendb might not be best.

sounds good

**Comment by SimonCropp** [comment]
needs a rebase

**Comment by SimonCropp** [comment]
@HEskandari the diff is now really stuffed. and still has conflicts.

**Comment by HEskandari** [comment]
@SimonCropp must be good now

**Pull request merged**
