### PR TITLE
Removed statement about `await Task.FromResult` from upgrade guide

### PR DESCRIPTION
**Pull request by danielmarbach**
The statement with `await Task.FromResult` was weird. Removed it for better clarity. It was also not clear to what "this" was referring to.

### CODE REVIEW

**Comment by danielmarbach** [comment]
The question is:

Should we still add

> You may mark your handle method `async`

? I think it is redundant since it is already stated above. Or maybe we can structure it better with subtitles about async vs sync handlers. Thoughts?

**Comment by indualagarsamy** [comment]
@danielmarbach - I like your idea of providing more info as Async vs Sync handlers.

**Comment by weralabaj** [comment]
Not sure how much you want to cover in "Async vs Sync handlers", would it make sense to make it a separate article (guidance content) and only link from here?
If that's just 2-3 sentences though then let's do it here.

**Comment by SimonCropp** [comment]
@indualagarsamy @weralabaj @danielmarbach happy with more info being provided elsewhere. but this PR is incrementally better and should not be blocked by a more significant effort in terms of documenting async

**Pull request merged**
