### PR TITLE
Update custom transport sample to core beta6

### PR DESCRIPTION
**Pull request by timbussmann**
basic sample works, but error handling is not working properly. Need to figure out how to work with these transactions.

### CODE REVIEW

**Comment by timbussmann** [comment]
@SimonCropp @andreasohlund do you think having a transaction mechanism adds a real value to this sample in the first place? (looking at the current state, the pasted code is already quite a lot to read through and not easy to grasp, by implementing the `onError` contract properly. this will potentially add quite a bit of code). It makes sense to have a sample how to use the transaction API, but could we also come up with a simpler sample for that?

**Comment by andreasohlund** [comment]
Since the sample is focued on the how to implement a transport perhaps we can just support "ReceiveOnly" and just delete all the (kid of irrelevant) transaction stuff?

**Comment by SimonCropp** [comment]
@andreasohlund @timbussmann isnt the transaction hoops relevant since in any real world transport people would have to do similar

**Comment by andreasohlund** [comment]
It depends, eg Rabbit and ASQ doesn't have any "transactions" so they just
supports `ReceiveOnly`.

Since transactions would be provided by the underlying queuing system I'd
say that this sample should focus on the seam and not how to implement TX
on top of a file system?

Is there a middle ground, perhaps just put a `//todo: implement
transactions` comment or something?

**Comment by timbussmann** [comment]
> Is there a middle ground, perhaps just put a `//todo: implement
transactions` comment or something?

we could point out at what place you would have to pass down your transactions with the `TransportTransaction` class.

Personally I'm :+1: on removing transactions. As @SimonCropp pointed out correctly, if we want to show how to implement transactional behavior, this would probably be the sample for, but I still think it makes the sample so much more complicated. Maybe we can show transaction implementation with a simpler in-memory transport instead as it's own sample?

**Comment by SimonCropp** [comment]
either way we have to solve the transactions. @andreasohlund plans on adding the file transport to the core in a future version. so if we already need to solve the error handling/transactions for that change i think we should just also include them in here

**Comment by timbussmann** [comment]
but wouldn't it make more sense to point to @andreasohlund production ready file transport implementation if interested how transactions work instead of having different implementations around?

How about removing the SendsAtomicWithReceive capabilities and use ReceiveOnly instead, that would allow us to do in-memory FLR which would make the transaction implementation simpler will still showing how to use transactions?

**Comment by SimonCropp** [comment]
> but wouldn't it make more sense to point to @andreasohlund production ready file transport implementation if interested how transactions work instead of having different implementations around?

Ok i am happy with that

**Comment by andreasohlund** [comment]
I'll make sure to update it to the new seam next week

**Comment by timbussmann** [comment]
@andreasohlund @Particular/docs-maintainers changed transaction handling to ReceiveOnly mode and implemented "proper" immediate retries. Please review.

**Comment by SzymonPobiega** [comment]
@timbussmann is it ready? If so, can you remove the `[WIP]` tag

**Comment by SzymonPobiega** [comment]
Also, it needs a rebase because the build is failing due to title restrictions on other pages that already have been fixed on master.

**Comment by timbussmann** [comment]
ah, will rebase

**Pull request merged**
