### PR TITLE
fabric to nsb v7

### PR DESCRIPTION
**Pull request by SimonCropp**
pending a service fabric persistence package being on myget

### CODE REVIEW

**Comment by SimonCropp** [comment]
ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
Likely no to be converted to v7 atm. See PlatDev [issue](https://github.com/Particular/PlatformDevelopment/issues/1440).

**Comment by danielmarbach** [comment]
@SimonCropp latest commit should make it compiling. There is still a smoke test pending from my side

**Comment by danielmarbach** [comment]
image

Smoke tested. Works

**Pull request merged**
