### PR TITLE
Securing the connection string

### PR DESCRIPTION
**Pull request by WilliamBZA**
Connects to https://github.com/Particular/docs.particular.net/issues/1277

### CODE REVIEW

**Comment by Scooletz** [comment]
:+1:

**Comment by WilliamBZA** [comment]
Ping @Particular/docs-maintainers this is ready for review

**Comment by weralabaj** [comment]
@WilliamBZA @Scooletz since we have a dedicated configuration page http://docs.particular.net/nservicebus/azure-storage-queues/configuration, wouldn't it make more sense to move all the "How to set up & secure connection string" content there?

**Comment by Scooletz** [comment]
Imho you're the one who proposes a layout for the doco @weralabaj

**Comment by weralabaj** [comment]
My proposition is to move it, but I want to make sure it makes sense from your perspective too :)

**Comment by WilliamBZA** [comment]
Happy to move. I'll update the PR.

A quick clarification on one of your changes @weralabaj: You changed the version part to say Version 6 and *lower* but the guidelines in the repo says to use the word [*below*](https://github.com/Particular/docs.particular.net/#version-language).

Are you happy for me to change back to below?

**Comment by weralabaj** [comment]
@WilliamBZA that's embarassing, I'd swear it was different before ;) I'll fix it don't worry. We need to rebase before we can move content though because you don't have updates from @Scooletz .

**Comment by weralabaj** [comment]
@WilliamBZA please, see if it makes sense and if I didn't violate any rules :D Thanks for catching it before!

**Pull request merged**
