### PR TITLE
[WIP] Update docos regarding SQL Server transport 3.0

### PR DESCRIPTION
**Pull request by weralabaj**
Connects to https://github.com/Particular/NServiceBus.SqlServer/issues/100

### CODE REVIEW

**Comment by SimonCropp** [comment]
@tmasternak should this be assigned to you?

**Comment by tmasternak** [comment]
:+1:

**Comment by SimonCropp** [comment]
@tmasternak can u rebase

**Comment by tmasternak** [comment]
@SimonCropp will do. However this one is no ready for review

**Comment by SimonCropp** [comment]
@tmasternak fwiw this pr is attempting to do too much in one go.

**Comment by tmasternak** [comment]
@SimonCropp I agree and in fact I've been pushing some overlapping parts in separate PR. I'm closing this one.

**Pull request closed without merging**
