### PR TITLE
[WIP] Wormhole ping pong sample Core V7

### PR DESCRIPTION
**Pull request by mauroservienti**
being based on MSMQ it's full framework only.

### CODE REVIEW

**Comment by mauroservienti** [comment]
@SzymonPobiega can you please take a look? The sample compiles and seems to function however sent messages never arrive to the expected destination. They are picked up by GatewayA but never delivered to GatewayB.

**Comment by SzymonPobiega** [comment]
@mauroservienti yeah, I'll check it today.

**Comment by SzymonPobiega** [comment]
@mauroservienti it seems like the gateway itself it broken for the current beta of V7 :-( I need to fix it before this sample could be merged.

**Comment by mauroservienti** [comment]
Thanks @SzymonPobiega I’ll leave this marked as WIP till the Gateway is fixed.

**Comment by andreasohlund** [comment]
>it seems like the gateway itself it broken for the current beta of V7 :-( I need to fix it before this sample could be merged.

Is this still true?

**Comment by SzymonPobiega** [comment]
Yeah. I didn't have time to work on this yet.

**Comment by andreasohlund** [comment]
What is actually broken with the GW?

**Comment by SzymonPobiega** [comment]
@andreasohlund The main issue was the difference in the distribution strategy APIs. It now compiles so I should be able to prepare an RC soon.

**Comment by SzymonPobiega** [comment]
@andreasohlund after giving it some thought I decided to not work on the wormhole for now and see if the bridge can be easily used instead. I propose to close this for now.

**Pull request closed without merging**
