### PR TITLE
Fixed 'index' page for MSMQ Subscription storage

### PR DESCRIPTION
**Pull request by dvdstelt**
This page is only accessible via search, but contained incorrect and very little data.

### CODE REVIEW

**Comment by janovesk** [comment]
LGTM

**Comment by dvdstelt** [comment]
Hmmm, the error is 
```
System.Exception : Path: 'C:\BuildAgent\work\542e5eb63d1ae8b\persistence\msmq\index.md'. Error: 'Error:'Path does not exist'. Url:'/persistence/msmq/subscription'.'
```
@Particular/docs-maintainers what am I doing wrong here?

**Comment by DavidBoike** [comment]
Subscription.md

**Comment by DavidBoike** [comment]
As "something" is definitely better than "nothing" I'm merging this.

**Pull request merged**
