### PR TITLE
[WIP] Updating scaleout docs with new distributor config

### PR DESCRIPTION
**Pull request by mat-mcloughlin**
Connects to https://github.com/Particular/NServiceBus/pull/3438

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@mat-mcloughlin I think this one is outdated. I think @SimonCropp already merged my PR that adds V6 version of that sample.

**Comment by mat-mcloughlin** [comment]
@SzymonPobiega Ah ok. I hadn't had time to look. I'd just created a temporary PR so I didn't forgot the documentation.

**Comment by mat-mcloughlin** [comment]
@SzymonPobiega I've checked with master and the only reference left to `DistributorControlAddress` and `DistributorDataAddress` is in this document:

https://github.com/Particular/docs.particular.net/blob/master/nservicebus/scalability-and-ha/distributor/index.md

Does this need much updating or will removing the reference be enough?

**Comment by SzymonPobiega** [comment]
I think removing is enough. Maybe a small note that in V6 we're retiring the distributor and you need to call that special API to enlist with a legacy distributor.

**Comment by mat-mcloughlin** [comment]
:+1:

**Comment by SimonCropp** [comment]
covered as part of this https://github.com/Particular/docs.particular.net/commit/1f9d4cbdc3ecf42d43f0a32ba37eee8dc2a8950f

@mat-mcloughlin can u do a new PR for the .md update

**Pull request closed without merging**
