### PR TITLE
Do a search and QA on usages of `IBus` in Doco

### PR DESCRIPTION
**Pull request by WojcikMike**
Connects to #1237

Blocked by definitions of Endpoint and Endpoint Instance requested in: #1278

### CODE REVIEW

**Comment by WojcikMike** [comment]
I reviewed the changes and I have no better idea how to write it.

**Comment by WojcikMike** [comment]
Currently I have following text:
>The simplest way to reply to a message is using the `Reply` method provided by the `IMessageHandlerContext` (in Version 6) or IBus (in Version 3-5), like this:

Should I rather go for below solution:
>The simplest way to reply to a message is using the `Reply` method, like this:

And allow for code to do the talking?
cc: @weralabaj @mikeminutillo @SimonCropp

**Comment by WojcikMike** [comment]
The same thing goes with:
>In order to send message to other sites you need to call the `IMessageHandlerContext.SendToSites` (in Version 6) or `IBus.SendToSites` (in Version 3-5).

Should I remove IBus and IMessageHandlerContext and simply mention method name and create sample? Thoughts?

**Comment by weralabaj** [comment]
Looking at other examples (e.g. http://docs.particular.net/samples/outbox/sqltransport-nhpersistence/#code-walk-through-receiver-project or http://docs.particular.net/nservicebus/sqlserver/configuration#connection-strings-via-a-named-connection-string) I'm +1 for leaving only method names.

> The simplest way to reply to a message is using the Reply method, like this: 

It could be even "The simplest way to reply to a message is using `Reply` method:

> In order to send message to other sites you need to call the IMessageHandlerContext.SendToSites (in Version 6) or IBus.SendToSites (in Version 3-5).

"In order to send message to other sites call `SendToSites` method:

**Comment by WojcikMike** [comment]
Ok, I introduced the changes, please review @Particular/docs-maintainers

**Pull request merged**
